import { Question } from './question';

export const questionsFr: Question[] = [
  {
    question: 'Combien cela va-t-il coûter ?',
    summary: 'En France, une <a target="_blank" href="https://www.conventioncitoyennepourleclimat.fr/budget/">initiative similaire</a> a coûté 5,4 millions d\'euros. Les dépenses ont été étroitement contrôlées par une commission d’audit indépendante, et réparties comme suit : 34% pour l’encadrement, l\'orientation et l\'organisation, 28% pour les dépenses et honoraires des membres, 16% pour la logistique et l’accueil, 9% pour la communication, 6% pour la communication avec le gouvernement, 5% pour les frais de tirage au sort, 2% pour les dépenses des experts. Ce montant peut paraître élevé mais il ne représente pas grand chose par rapport au mandat d’un Parlement Citoyen sur l’urgence écologique. Il est également relativement bas comparé, par exemple, au <a target="_blank" href="https://www.senate.be/event/20191213-budget/20191213-budget_nl.html">budget du Sénat belge</a>, une institution qui n\'a pratiquement plus aucun pouvoir et dont le budget annuel s\'élève à 46 millions d\'euros. Ou bien comparez cela aux 70 millions d\'euros de subventions que les partis belges réunis reçoivent chaque année.',
    answer: '',
    tags: ['parlement', 'pratique', 'budget', 'cher', 'prix'],
    slug: 'ca-va-couter-combien',
  }, {
    question: 'Qui va payer les frais ?',
    summary: 'L\'État fédéral. En France, la Convention Citoyenne pour le climat mise en place par le Président Emmanuel Macron a été financée par le budget de l’Etat.',
    answer: '',
    tags: ['parlement', 'pratique', 'budget', 'cher', 'prix'],
    slug: 'qui-va-payer-les-frais',
  }, {
    question: 'Cette proposition est tout de même complètement irréaliste ?',
    summary: 'Cela dépend de quelle « réalité » vous parlez. La réalité politique ou la réalité de la crise écologique ? Dans ce dernier cas, nos responsables politiques nationaux et internationaux ne la prennent pas encore suffisamment au sérieux, c’est le moins que l’on puisse dire. Il semble parfois qu’ils vivent sur une autre planète que celle des scientifiques de l’environnement. Si l’on se place du point de vue de la réalité politique belge actuelle, établir un Parlement citoyen n’est certainement pas une affaire facile. De nombreux partis ont peur, malgré la mention du « renouveau démocratique » comme l’une des priorités dans l’accord de coalition du gouvernement De Croo. Et pourtant : nous ne demandons pas une révolution constitutionnelle majeure. Nous tenons simplement compte de la complexité administrative existante dans ce pays. Dans <a target="_blank" href="https://www.leparlementcitoyen.be/assets/proposal/le_parlement_citoyen_proposition.pdf">la version longue et détaillée de notre proposition</a>, vous pouvez lire plus précisément comment le Parlement citoyen pourrait procéder. Un tel plan semble parfaitement réalisable. Libérer le budget fédéral nécessaire à cette initiative ne doit pas non plus être insurmontable. Si 46 millions d’euros par an peuvent aller au Sénat, une institution qui n’a pratiquement plus de pouvoirs, cela devrait être possible, n’est-ce pas ?',
    answer: '',
    tags: ['parlement', 'pratique', 'budget', 'cher', 'prix', 'politique', 'science', 'exemples'],
    slug: 'cette-proposition-est-completement-irrealiste',
  }, {
    question: 'Le pouvoir de s’attaquer à la crise écologique ne se situ-t-il pas principalement au niveau Européen ?',
    summary: 'L’un des concepts les plus importants pour réfléchir à la bonne gouvernance est celui de la « subsidiarité » : quel niveau a besoin de quelle politique et inversement ? En Belgique, la nature multidimensionnelle de la gouvernance, divisée entre autres en un État fédéral, des Communautés et des Régions, conduit parfois à les politiques à se pointer du doigt les uns les autres, et à reporter sur autrui les tâches et responsabilités. Cependant, l’urgence de la crise écologique (une « contrainte » similaire à celle de la crise du coronavirus) oblige notre pays à mener des politiques et une coopération cohérentes. La Commission européenne nous l’a récemment <a target="_blank" href="https://www.demorgen.be/politiek/europa-kritisch-voor-belgisch-klimaatplan-geen-coherent-geheel~b1db58c4/">fait remarquer</a> lors de l’évaluation critique du Plan Climat belge. Dans le cas de l’urgence écologique, la question de la subsidiarité est particulièrement complexe, étant donné la nature « glocale » (globale et locale) de la crise. De nombreux instruments politiques pour faire face à cette crise sont situés au niveau de l’Union européenne plutôt qu’à celui de la petite Belgique. Bien que des propositions soient en cours d’élaboration pour un Parlement européen des citoyens, il nous semble important de prendre les mesures nécessaires en Belgique également ; ceci non à pas de souris mais avec des bottes de sept lieues. Les représentants politiques des différents niveaux ne peuvent plus se permettre de s’attendre les uns les autres. Tout le monde devrait être sur le pont.',
    answer: '',
    tags: ['politique', 'belgique', 'europe', 'eu', 'niveau'],
    slug: 'le-pouvoir-de-sattaquer-a-la-crise-ecologique-ne-se-situ-t-il-pas-principalement-au-niveau-europeen',
  }, {
    question: 'Pourquoi le Parlement citoyen ne traite-t-il qu’un seul thème, celui de la crise écologique ?',
    summary: 'La crise écologique n’est pas « un seul thème » ; le plus grand défi auquel l’humanité est confrontée a un impact sur tous les domaines de la société. Un Parlement citoyen aborderait donc les thématiques suivantes, que chaque citoyen peut facilement relier à sa vie quotidienne : (1) approvisionnement alimentaire, agriculture et gestion de l’environnement, (2) travail, (3) logement et aménagement du territoire, (4) mobilité et transport, (5) production et utilisation des matières premières, (6) consommation, (7) énergie. Certains problèmes et certaines solutions possibles se posent simultanément dans plusieurs thématiques. C’est pourquoi nous proposons d\'inclure une formation à la pensée systémique dans la première session du Parlement citoyen (une telle formation peut se faire de manière très pragmatique). On veillera également à ce que les citoyens changent régulièrement de groupe thématique tout au long du processus de délibération, ce qui facilitera la création des liens nécessaires sur le fond. La crise est « écologique » de bout en bout (tout est lié à tout de manière complexe) ; la réponse à cette crise devra l’être de même.',
    answer: '',
    tags: ['crise écologique', 'ecologie', 'organisation', 'pratique'],
    slug: 'pourquoi-le-parlement-citoyen-ne-traite-que-le-theme-de-la-crise-ecologique',
  }, {
    question: 'Quelle est la différence avec le G1000 ?',
    summary: 'Le G1000 a été une expérience importante au moment de la crise politique de 2010-2011, lorsque notre pays a établi le record mondial du temps nécessaire pour la formation du gouvernement (541 jours). C’était quelque chose de tout à fait différent de ce que nous proposons : l’événement central du G1000 n’a duré qu’une journée – nous pensons pour le Parlement citoyen à 11 sessions de trois jours réparties sur une année, ce qui est absolument nécessaire pour une information approfondie et une délibération valable. Les citoyens sélectionnés ont ensuite été consultés sur divers sujets qui n’étaient pas directement liés entre eux. Le Parlement citoyen se concentrerait sur la crise écologique. L’une des critiques sur le G1000 était que le groupe d’experts invités n’était pas suffisamment équilibré. Nous plaidons pour un équilibre idéologique qui tienne compte du consensus scientifique autour de la crise écologique. Avec 700 participants, le G1000 a été une énorme entreprise logistique. Pour un parlement citoyen qui fonctionne bien, vous n’avez pas besoin d’autant de monde, nous pensons à 101 membres. Le G1000 était une initiative grassroots qui a rassemblé son propre budget. Dans notre cas, seule la présente campagne est grassroots, nous appelons le gouvernement à initier, financer et défendre publiquement le Parlement citoyen. Cela lui donne immédiatement plus de poids politique. Le G1000 a eu lieu il y a 10 ans. Depuis lors, une grande expérience a été accumulée. La méthodologie est maintenant plus à jour. Le G1000 était principalement une déclaration symbolique en 2010-2011. Il faut maintenant dépasser le symbolisme.',
    answer: '',
    tags: ['organisation', 'pratique', 'tirage au sort'],
    slug: 'quelle-est-la-difference-avec-le-G1000',
  }, {
    question: 'N’est-ce pas une idée marginale ?',
    summary: 'Beaucoup de pays nous ont précédés : France, Irlande, Corée du Sud, Australie, Grande-Bretagne... Ils ont organisé des parlements citoyens autour de sujets variés. Aujourd’hui, même l’OCDE – pas vraiment un groupe marginal, en tant qu’alliance économique de pays riches – plaide en faveur de la démocratie délibérative. Selon une étude récente du CEVIPOL, 75,8 % des Belges sont favorables à une assemblée de citoyens sélectionnés par tirage au sort. En outre, le gouvernement De Croo affirme dans son accord de coalition s’engager en faveur du « renouveau démocratique », une compétence qui relève du Ministère de l’Intérieur, dirigé par Annelies Verlinden (CD&V).',
    answer: '',
    tags: ['démocratie', 'pratique', 'niveau'],
    slug: 'nest-ce-pas-une-idee-marginale',
  }, {
    question: 'Le grand public ressent-il suffisamment d’urgence pour soutenir cette proposition ?',
    summary: 'Les négationnistes climatiques chevronnés nous semblent être une très petite minorité en Belgique. Néanmoins, une grande partie de la population ne voit pas la gravité de la crise écologique, ni la vitesse à laquelle elle se déroule. Par contre, il existe un consensus parmi les scientifiques : l’habitabilité de notre planète est en jeu. Une raison importante de l’absence d\'urgence est liée à la fourniture d’informations. Le journal britannique The Guardian a publié l’année dernière 3000 articles sur l’environnement et le climat. Sur le petit marché belge, les médias d’information doivent faire face à une forte pression commerciale. De ce point de vue, publier sur une crise hyper-complexe, accablante et parfois un peu ennuyeuse et technique est toujours un risque. Trump contre Biden se lit mieux et se vend mieux. Souvent, les rédacteurs en chef des journaux, magazines et revues n’ont pas les connaissances nécessaires pour vraiment rendre compte de la profondeur de la crise écologique, à quelques exceptions près. De plus, non seulement cette vérité est particulièrement complexe et quelque peu abstraite car pas encore pleinement visible dans notre vie quotidienne ; mais c’est aussi un message qui n’est pas très édifiant. Pourtant, nous devons oser affronter cette crise en tant que société, et le plus tôt le mieux.',
    answer: '',
    tags: ['crise écologique', 'complexité'],
    slug: 'le-grand-public-ressent-il-suffisamment-durgence-pour-soutenir-cette-proposition',
  }, {
    question: 'Et si les membres d’un Parlement citoyen nient l’existence de la crise écologique ?',
    summary: 'C’est tout à fait possible, bien que les négationnistes chevronnés du climat semblent être une minorité en Belgique. De plus, l’expérience de la Convention Citoyenne pour le Climat française montre que les citoyens qui ne se préoccupent guère du climat ou de l’environnement le font après avoir entendu les scientifiques qui viennent s’exprimer en tant qu’experts. Les mesures proposées à la fin du processus par les 150 membres de la Convention – situés à gauche et à droite sur l’échiquier politique – allaient bien au-delà de ce que le représentant politique moyen met à l’ordre du jour aujourd’hui.',
    answer: '',
    tags: ['pratique', 'tirage au sort', 'climat'],
    slug: 'et-si-les-membres-dun-parlement-citoyen-nient-lexistence-de-la-crise-ecologique',
  }, {
    question: 'Un Parlement citoyen ne dépouille-t-il pas le débat politique de sa dimension idéologique ? ',
    summary: 'Plaider pour un environnement habitable n’est pas une question de droite ou de gauche. Cependant, les préférences idéologiques peuvent jouer un rôle quand on veut proposer des mesures concrètes à atteindre se but. Si vous réunissez un groupe de citoyens tirés au sort qui sont représentatifs de la population totale, en tenant compte de différents critères démographiques, ces différentes préférences sont présentes à la table de discussion. Toutefois, de nombreuses initiatives antérieures ont montré que lorsque ces citoyens prennent connaissance des intérêts et des perspectives des autres, ils deviennent plus diplomatiques et moins stables sur le plan idéologique. Le fait de dépasser l’omniprésente polarisation politique garantit une prise de décision plus efficace et mieux soutenue, surtout lorsqu’il s’agit de questions controversées. La Convention Citoyenne pour le Climat française montre cependant qu’une fois que les citoyens ont soumis leur liste de propositions aux politiciens, le jeu politique n’est plus joué. Le président français Emmanuel Macron a d’abord promis de mettre en œuvre la grande majorité des propositions de la Convention, mais quelques mois plus tard, un lobbying actif et une opposition politique ont empêché de tenir une grande partie de cette promesse. Le rôle des hommes politiques et de la société civile au sens large reste donc très important après un processus de délibération. Un dernier point : ne confondons pas les grands intérêts économiques d’une très petite minorité avec des différences d’opinion idéologiques. L’idéologie est souvent utilisée à mauvais escient comme un écran de fumée.',
    answer: '',
    tags: ['politique', 'polarisation', 'idéologie'],
    slug: 'un-parlement-citoyen-ne-depouille-t-il-pas-le-debat-politique-de-sa-dimension-ideologique',
  }, {
    question: 'N’avez-vous pas une idée trop naïve du fonctionnement du pouvoir ?',
    summary: 'Il est évident que lorsque l’on réfléchit à des mesures à la lumière de la crise écologique, les intérêts économiques majeurs d’une très petite minorité de la population sont en jeu. La Convention Citoyenne pour le Climat française a démontré que cette très petite minorité a beaucoup de pouvoir. Au départ, le président français Emmanuel Macron prétendait mettre en œuvre la grande majorité des propositions de la Convention, mais quelques mois plus tard, un lobbying actif et une opposition politique ont fait que cette promesse n\'a guère été tenue. Le rôle des hommes politiques et de la société civile au sens large reste donc très important après un processus de délibération. Nous pensons qu’il est plus difficile pour une très petite minorité d’acteurs de faire pression sur un groupe de 101 citoyens tirés au sort que sur des politiciens élus. Il est également moins facile d’abattre les propositions de ce groupe de citoyens, représentatif de la population totale, que les propositions d’un seul parti politique. Les différences d’opinion idéologiques sont souvent utilisées comme un écran de fumée. Du point de vue de la politique de pouvoir, un Parlement citoyen nous semble donc être une initiative précieuse.',
    answer: '',
    tags: ['politique', 'pouvoir', 'démocratie', 'idéologie', 'lobby'],
    slug: 'navez-vous-pas-une-idee-trop-naive-du-fonctionnement-du-pouvoir',
  }, {
    question: 'En France, une initiative similaire a échoué, n’est-ce pas ?',
    summary: 'La Convention Citoyenne pour le Climat a fait œuvre de pionnière dans plusieurs domaines : la conception du processus de délibération, le soutien financier et public initial du président Macron, les 149 propositions détaillées des 150 citoyens français... Mais en effet, la Convention présente aussi des défauts fondamentaux. Au départ, Macron promettait mettre en œuvre la grande majorité des propositions de la Convention, mais quelques mois plus tard, un lobbying actif et une opposition politique ont fait que cette promesse n’a pas été tenue. Selon nous, cela montre que le rôle des hommes politiques et de la société civile au sens large reste donc très important après un processus de délibération. Il nous semble également crucial que les politiciens défendent publiquement l’idée face à la population en général – avec un large soutien public pour un Parlement citoyen, ils sont beaucoup plus forts face au pouvoir réel d’une très petite minorité ayant de grands intérêts économiques.',
    answer: '',
    tags: ['parlement', 'ccc', 'exemples'],
    slug: 'en-france-une-initiative-similaire-a-echoue',
  }, {
    question: 'Vous n’êtes que les pantins d’Ecolo',
    summary: 'Nous sommes un groupe de citoyen.ne.s préoccupé.e.s par la crise écologique, sans aucun lien avec les Ecolo, Groen ou tout autre parti politique. Bien que chacun.e d\'entre nous ait ses préférences idéologiques, nous voulons impliquer tout le monde dans la discussion sur les énormes défis posés par la crise écologique, qui ne connaît ni gauche ni droite. Le Parlement Citoyen est constitué d\'un groupe de citoyen.ne.s représentatif.ve.s de l\'ensemble de la population belge. Toutes les tendances idéologiques y seront donc représentées.',
    answer: '',
    tags: ['organisation', 'idéologie', 'écologie', 'partis', 'partisan'],
    slug: 'vous-netes-que-les-pantins-decolo',
  }, {
    question: 'Qui a financé cette campagne ?',
    summary: 'Personne. Cette campagne coûte n’a absolument rien coûté et repose sur l\'engagement de nombreux bénévoles.',
    answer: '',
    tags: ['organisation', 'campagne', 'financement'],
    slug: 'qui-a-finance-cette-campagne',
  }, {
    question: 'Comment les citoyen.ne.s sont-iels tiré.e.s au sort ?',
    summary: 'Le processus de tirage au sort dure environ six semaines. Dans un premier temps, une vaste base de données incluant tout.e.s les habitant.e.s du pays est constituée. Ensuite, un certain nombre de personnes sélectionnées au hasard dans la base de données sont invitées par téléphone et par courrier. L\'invitation contient des informations quant à la la tâche du Parlement Citoyen et fournit des informations sur les dates, le lieu, le logement, les frais, ainsi que les indemnités et aides disponibles pour les voyages et les services de garde. Le groupe de personnes ayant répondu à l\'invitation est ensuite systématiquement complété par de nouveaux échantillons aléatoires. Des critères démographiques tels que le sexe, l\'âge, le niveau d\'éducation, la catégorie socioprofessionnelle, la répartition géographique, le type de zone résidentielle, etc. sont pris en compte.',
    answer: '',
    tags: ['tirage au sort', 'représentativité'],
    slug: 'comment-les-citoyennes-sont-ils-tirées-au-sort',
  }, {
    question: 'Pourquoi ne pas organiser vous-mêmes le Parlement Citoyen ?',
    summary: 'Ce ne serait pas une bonne idée. Afin de garantir l’impartialité du processus, les citoyen.ne.s à l’initiative de cette proposition ne devraient jouer de rôle ni dans l\'organisation générale, ni dans la sélection des experts, et ni dans la supervision du projet. Le Parlement Citoyen doit rester aussi indépendant que possible de tout acteur politique, économique ou social. Il est initié et financé par le gouvernement fédéral. Un groupe de coordination, un conseil consultatif, une équipe de facilitation, un comité juridique et un groupe de suivi assurent ensemble la transparence publique, l\'indépendance politique et la légitimité démocratique du processus.',
    answer: '',
    tags: ['organisation', 'transparence', 'légitimité', 'partisan'],
    slug: 'pourquoi-ne-pas-organiser-vous-memes-le-parlement-citoyen',
  }, {
    question: 'Comment un Parlement Citoyen peut-il être réellement représentatif ?',
    summary: 'Lors du tirage au sort des membres d\'un parlement citoyen, des critères démographiques tels que le sexe, l\'âge, le niveau d\'éducation, les catégories socioprofessionnelles, la répartition géographique, le type de zone résidentielle, etc. sont pris en compte. Cela rend un parlement citoyen bien plus représentatif que les parlements tels que nous les connaissons. Par exemple, un cinquième des membres du Parlement sont des avocats, alors que moins d’1 % des Belges le sont. On ne trouve pas non plus beaucoup d’ouvrier.e.s ni d’agriculteurs.trices sur ses bancs. Combien de parlements dans le monde peuvent se vanter de compter 29% de membres peu qualifiés, à la manière de la Convention Citoyenne pour le Climat en France ? Le spectre étroit des connaissances et des expériences de vie dans les parlements existants porte préjudice à la démocratie. Un tirage au sort intelligent garantit une plus grande représentativité, dont découlent des propositions politiques bénéficiant d’un plus large consensus et donc une plus grande légitimité.',
    answer: '',
    tags: ['tirage au sort', 'légitimité'],
    slug: 'comment-un-parlement-citoyen-peut-il-etre-vraiment-representatif',
  }, {
    question: 'Le Parlement Citoyen est-il suffisamment inclusif ?',
    summary: 'Bonne question. Malgré le système de tirage au sort représentatif, il existe des obstacles importants à la participation. L’obstacle financier peut être surmonté au moyen d’indemnités journalières, de transport et de logement. Des services de garde d\'enfants sont fournis, une aide est apportée pour les soins aux personnes âgées, les soins aux membres de la famille avec un handicap, … En cas de besoin (par exemple pour les enseignants), un remplacement est assuré. Par ailleurs, il existe également des barrières linguistiques: certain.e.s citoyen.ne.s, de par leur éducation, leurs conditions de vie privilégiées ou leur caractère extraverti, s\'expriment plus facilement que d\'autres. Une courte formation pour apprendre à parler et à écouter en groupe peut atténuer les différences existantes, et chaque conversation de groupe doit être modérée avec le plus grand soin.',
    answer: '',
    tags: ['tirage au sort', 'inclusion', 'modération', 'représentativité', 'XXXXXX', 'XXXXXX', 'XXXXXX'],
    slug: 'le-parlement-citoyen-est-il-suffisamment-inclusif',
  }, {
    question: 'N\'y a-t-il pas déjà beaucoup d\'initiatives de participation citoyenne ?',
    summary: 'Beaucoup de ces initiatives ne font pas appel au tirage au sort représentatif, ce qui entraîne une surreprésentation des personnes disposant de beaucoup de temps, au détriment de la diversité. Ce genre de participation citoyenne est contre-productive. En outre, la crise écologique exige une approche large et transversale, à différents niveaux de gouvernement, et dans une perspective à long terme. Les organes consultatifs plus petits et moins visibles autour de questions spécifiques n\'ont pas l\'élan nécessaire. Enfin, le pouvoir de nombreux organismes de participation citoyenne est très limité. Dans notre initiative, aucune des propositions des citoyen.ne.s n\'est perdue; soit elles sont mises en œuvre par le(s) gouvernement(s) compétent(s), soit elles sont votées dans le(s) parlement(s) compétent(s). Si une proposition est rejetée, le rejet devra être argumenté publiquement et en profondeur.',
    answer: '',
    tags: ['démocratie', 'pouvoir', 'tirage au sort'],
    slug: 'deja-beaucoup-dinitiatives-de-participation',
  }, {
    question: 'Le panel d\'experts sera-t-il composé uniquement d\'universitaires de gauche ?',
    summary: 'Non, ce ne sera pas le cas. Il est essentiel d\'informer les membres du Parlement Citoyen de manière pluraliste. Le panel sera composé d\'experts et des parties prenantes, soit des représentants de ceux.celles dont les intérêts et/ou les droits sont menacés ou qui justement pourraient bénéficier d\'éventuelles mesures). Cependant, il est important que la composition du panel tienne compte du consensus scientifique sur la crise écologique. Il est également nécessaire que des voix très différentes et parfois contradictoires soient entendues. Lors de la Convention Citoyenne pour le climat, des climatologues, des écologistes, des juristes, des journalistes, des militants, des architectes, des représentants de l\'industrie, de la construction, de l\'agriculture, de l\'énergie, des transports et de la mobilité, des ministères, des syndicats, des fonctionnaires, des ONG, des groupes de réflexion, etc. ont pris la parole.',
    answer: '',
    tags: ['parlement', 'experts', 'information', 'science'],
    slug: 'panel-dexperts-sera-compose-duniversitaires-de-gauche',
  }, {
    question: 'Les politiciens n\'accepteront jamais cette proposition puisqu’elle leur enlève du pouvoir ?',
    summary: 'C’est une bonne question. En effet, si les politiciens n’avaient qu\'à y perdre, notre proposition devrait être considérée irréaliste. Et lorsqu’une idée, même bonne et nécessaire, est politiquement irréaliste, elle reste lettre morte. Heureusement, les initiative qui nous ont precede, telles que le Parlement citoyen irlandais sur l\'avortement, montrent que cette forme de démocratie citoyenne renforce le pouvoir des politiciens plutôt que de l’affaiblir. Elle leur permet tout simplement de mener une politique environnementale plus ambitieuse. En outre, les politiciens mécontents du système institutionnel ankylosé dont ils font partie sont nombreux.',
    answer: '',
    tags: ['politique', 'pouvoir', 'démocratie'],
    slug: 'politiciens-accepteront-jamais-cette-proposition',
  }, {
    question: 'Voulez-vous abolir les parlements existants ?',
    summary: 'Non, absolument pas. Nous ne proposons pas de remplacer un système (avec des citoyen.ne.s élu.e.s) par un autre (avec des citoyen.ne.s tiré.e.s au sort). La démocratie citoyenne renforce la représentation élue. Il nous semble que malheureusement la majorité des citoyen.ne.s flamand.e.s, wallon.ne.s, bruxellois.es et belges sont d\'accord avec nous sur ce point: après les interminables négociations pour la formation du gouvernement, la politique de parti belge pourrait vraiment sortir renforcée de ce processus.',
    answer: '',
    tags: ['démocratie', 'tirage au sort', 'élections'],
    slug: 'voulez-vous-abolir-les-parlements-existants',
  }, {
    question: 'Pourquoi 101 citoyen.ne.s choisis au hasard pourraient-ils décider à ma place ?',
    summary: 'C’est une question cruciale. Quelle est la légitimité démocratique d\'un Parlement Citoyen? Bien que les négociations gouvernementales passées aient sérieusement porté atteinte à la légitimité des partis politiques, la majorité de la population considère toujours les élections comme la seule option démocratique. Les politiciens élus décident eux aussi à la place des autres. Néanmoins, certains facteurs doivent être pris en compte dans la perception de que nous avons de leur légitimité: (a) Nos parlements actuels sont peu représentatifs de la diversité de la population. Il y a beaucoup d\'avocats, et peu de travailleurs, d\'agriculteurs et de personnes issues de l\'immigration, par exemple. (b) Un Parlement Citoyen tire sa légitimité du système de tirage au sort représentatif, des garanties d\'inclusivité, des contrôles et équilibres intégrés dans la structure organisationnelle, de la transparence du processus, etc. (c) Enfin, l\'argument le plus convaincant : les décisions du Parlement Citoyen sont toujours mises en œuvre ou votées par des politiciens élus.',
    answer: '',
    tags: ['démocratie', 'légitimité', 'représentativité', 'transparence', 'tirage au sort', 'élections'],
    slug: 'pourquoi-citoyens-choisis-au-hasard-pourraient-ils-decider-a-ma-place',
  }, {
    question: 'J\'ai des jeunes enfants. Alors je ne peux pas participer ?',
    summary: 'Oui, vous le pouvez. Dans certains cas en effet il existe des obstacles importants à la participation. L’obstacle financier peut être supprimé avec les indemnités journalières, les indemnités de transport et du logement. Des services de garde d\'enfants sont également proposés, ainsi qu\'une aide pour les soins aux personnes âgées, les soins aux membres de la famille avec un handicap, etc. les éventuels remplacements sont facilités en cas de besoin (par exemple, pour les enseignants).',
    answer: '',
    tags: ['pratique', 'inclusivité', 'remboursement'],
    slug: 'Jai-de-jeunes-enfants-alors-je-ne-peux-pas-participer',
  }, {
    question: 'Je dois travailler. Alors je ne peux pas participer ?',
    summary: 'Oui, le vous pouvez. Chaque membre bénéficie d’indemnités journalières, (y compris pour les travaux préparatoires nécessaires), des indemnités de transport et de logement. Les responsabilités familiales peuvent également empêcher les gens de consacrer du temps aux activités du Parlement Citoyen. C\'est pourquoi des services de garde d\'enfants sont proposés, une aide aux soins des personnes âgées, des soins aux membres de la famille avec un handicap, ... Les travailleurs bénéficient d\'un congé parlementaire citoyen, financé par le gouvernement. Un remplacement est facilité en cas de besoin (par exemple, pour les enseignants).',
    answer: '',
    tags: ['pratique', 'inclusivité', 'compensation'],
    slug: 'je-dois-travailler-alors-je-ne-peux-pas-participer',
  }, {
    question: 'Le parlement "ordinaire" est aussi un "parlement de citoyen.ne.s", n\'est-ce pas ?',
    summary: 'Ah, touché ! Oui, c\'est exact. Les politiciens sont aussi des citoyen.ne.s ! Pourtant, il existe des différences cruciales entre un parlement dont les citoyen.ne.s sont élus et un autre dont les membres sont tirés au sort. Le second est beaucoup plus représentatif de la diversité de la population. On ne trouve pas beaucoup d’ouvriers ni d’agriculteurs sur les bancs du parlement élu. (Quel parlement dans le monde pourrait-il prétendre que 29% de ses membres sont peu éduqués, comme la Convention Citoyenne pour le Climat en France ?) De plus, les citoyen.ne.s tirés au sort ne sont pas liés à une logique de parti. Ils ne doivent pas suivre les directives des cadres de leur parti. Ils ne doivent pas non plus s\'engager dans des querelles idéologiques tranchantes et médiatisées. Lorsqu\'ils se familiarisent avec les intérêts et les perspectives des nombreux autres participants, ils deviennent plus diplomatiques et beaucoup moins rigides sur le plan idéologique. Transcender la polarisation politique permet une prise de décision plus efficace et donc plus rapide. Contrairement à la logique de la concurrence, les parlements citoyen.ne.s considèrent la démocratie comme un moyen de coopération.',
    answer: '',
    tags: ['parlement', 'idéologie', 'coopération', 'polarisation', 'représentativité'],
    slug: 'le-parlement-ordinaire-est-aussi-un-parlement-de-citoyens',
  }, {
    question: 'Pourquoi ne pas communiquer en allemand ?',
    summary: 'Nous ne voulons bien évidemment pas exclure nos compatriotes germanophones ! Cependant, nous ne pouvons pas être plus catholiques que le pape, en ce qui concerne cette question, surtout en tant que responsables d\'une campagne qui coûte littéralement zéro euro et qui repose sur l\'engagement de nombreux bénévoles. D\'ailleurs, combien de sites web belges ont une version en langue allemande en plus d\'une version en langue française et néerlandaise ? C\'est pourquoi nous adressons ce message aux habitants des Cantons de l\'Est : Entschuldigung pour notre pragmatisme linguistique !',
    answer: '',
    tags: ['organisation', 'campagne', 'inclusivité'],
    slug: 'pourquoi-ne-pas-communiquer-en-allemand',
  }, {
    question: 'Comment gérer la complexité institutionnelle belge ?',
    summary: 'Oui, en Belgique, à la complexité de la crise écologique s’ajoute la complexité de la structure de l\'État et de la répartition des pouvoirs. Pas moins de quatre ministres s\'occupent de la politique climatique, neuf de la santé publique. Chez nous, cela entraîne souvent des retards ou des blocages administratifs; sur la scène politique internationale, l\'image de notre pays est ternie chaque fois qu\'il n’arrive pas à la table des négociations avec une position unifiée. Bien que le Parlement Citoyen serait mis en place et financé au niveau fédéral, nous proposons que chacune des propositions politiques disposant d’un un soutien suffisant parmi ses membres, soit mise en œuvre par le(s) gouvernement(s) compétent(s) ou soumise au(x) parlement(s) compétent(s) pour un vote. Bien qu\'une politique environnementale ambitieuse et cohérente doit être élaborée au niveau fédéral (en partie parce que c’est à ce e niveau que la Belgique peut s\'exprimer sur la scène politique internationale), la réalité administrative belge est que les compétences sont réparties entre les communautés, les régions et le niveau fédéral. Chaque proposition citoyenne doit donc recevoir un label indiquant dans quel(s) cadre(s) administratif(s) elle doit être traitée (c\'est-à-dire votée ou mise en œuvre). Les propositions rejetées seront toujours suivies de justifications publiques approfondies, qui puissent être vues, entendues ou lues par tous les Flamands, Wallons, Bruxellois et Belges germanophones. Les parlements compétents devront ensuite vérifier si les gouvernements correspondants appliquent correctement les mesures. Si un niveau de gouvernement (en raison de la composition spécifique de sa coalition) décide de ne pas soumettre au vote de son parlement les propositions des citoyen.ne.s tirés au sort au niveau fédéral, il appartiendra aux générations présentes et futures de porter un jugement moral sur cette décision.',
    answer: '',
    tags: ['politique', 'régions', 'communautés', 'complexité'],
    slug: 'comment-gerer-la-complexite-institutionnelle-belge',
  }, {
    question: 'Vous n\'allez quand même pas m’enlever ma voiture ?',
    summary: 'Nous n’allons <i>rien faire</i> de tel. Afin d\'éviter tout semblant de partialité, les citoyen.ne.s à l\'origine de cette proposition ne veulent pas jouer eux-mêmes un rôle dans l\'organisation de l\'ensemble du processus, la sélection des experts ou la supervision du Parlement Citoyen. Les mesures concrètes seront proposées par le Parlement Citoyen dans lequel les sièges sont occupés par des citoyen.ne.s avec des profils et des idéologies différents.',
    answer: '',
    tags: ['organisation', 'idéologie', 'écologie', 'science', 'voiture', 'émissions'],
    slug: 'vous-nallez-quand-meme-pas-menlever-ma-voiture',
  }, {
    question: 'Allez-vous m’interdire de manger de la viande ?',
    summary: 'Nous n’allons <i>rien faire</i> de tel. Afin d\'éviter tout semblant de partialité, les citoyen.ne.s à l\'origine de cette proposition ne veulent pas jouer eux-mêmes un rôle dans l\'organisation de l\'ensemble du processus, la sélection des experts ou la supervision du Parlement Citoyen. Les mesures concrètes seront proposées par le Parlement Citoyen dans lequel les sièges sont occupés par des citoyen.ne.s avec des profils et des idéologies différents.',
    answer: '',
    tags: ['organisation', 'idéologie', 'écologie', 'science', 'steak', 'émissions'],
    slug: 'allez-vous-minterdire-de-manger-de-la-viande',
  }, {
    question: 'Pourquoi ne pas vous lancer vous-même dans la politique ?',
    summary: 'N\'y a-t-il pas déjà assez de partis politiques ? Nous sommes des citoyen.ne.s inquiets qui constatons que les moyens politiques existants ne sont apparemment pas suffisants pour arriver à des mesures de gestion qui prennent au sérieux le consensus scientifique sur la crise écologique. Les élections entraînent de longues négociations de formation d’un gouvernement. Les manifestations et les grèves scolaires n\'apportent pas le changement nécessaire. Un Parlement Citoyen où tout le monde - jeunes et vieux, hommes et femmes, personnes avec différents degrés d’instruction - peut participer, peut être un moyen de franchir les étapes nécessaires. Il est essentiel que ses membres n\'aient pas à être réélus et osent ainsi plus facilement penser à long terme. Ils sont ainsi beaucoup moins sensibles au lobbying et ils n\'ont pas besoin d\'être constamment en désaccord devant la caméra ; ils peuvent s\'écouter et travailler ensemble !',
    answer: '',
    tags: ['politique', 'parti', 'idéologie', 'élections'],
    slug: 'pourquoi-ne-pas-vous-lancer-vous-meme-dans-la-politique',
  }, {
    question: 'Ne devrions-nous pas plutôt aller manifester ?',
    summary: 'Les moyens politiques existants ne sont apparemment pas suffisants pour arriver à des mesures de gestion qui prennent au sérieux le consensus scientifique sur la crise écologique. Les élections entraînent de longues négociations de formation d’un gouvernement. Les manifestations et les grèves scolaires n\'apportent pas le changement nécessaire. Un Parlement Citoyen où tout le monde - jeunes et vieux, hommes et femmes, personnes avec différents degrés d’instruction - peut participer, peut être un moyen de franchir les étapes nécessaires.',
    answer: '',
    tags: ['politique', 'élections'],
    slug: 'ne-devrions-nous-pas-plutot-aller-manifester',
  }, {
    question: 'Ces questions ne sont-elles pas trop difficiles pour les simples citoyen.ne.s ?',
    summary: 'Personne ne niera que la crise écologique est un sujet complexe. Mais ce n\'est pas une raison pour l\'éviter. C\'est précisément pour cette raison qu\'il est important d\'informer correctement les citoyen.ne.s à ce sujet, par le biais des médias et de l\'éducation. Les membres d\'un Parlement Citoyen seront informés de manière approfondie par un large éventail d\'experts au début de leur travail. C\'est la seule façon pour eux de faire des propositions politiques motivées. Ces informations sont, bien entendu, fournies de la manière la plus accessible possible. Il est de la plus haute importance que chacun puisse participer à ce débat, quel que soit son niveau d’éducation. Il est également bon de garder à l\'esprit que les hommes politiques ne sont souvent pas des experts dans les domaines politiques dans lesquels ils travaillent. Eux aussi sont(dans le meilleur des cas) bien informés par d’autres personnes lorsqu\'ils élaborent une politique.',
    answer: '',
    tags: ['démocratie', 'complexité', 'formation', 'experts'],
    slug: 'trop-difficiles-pour-les-simples-citoyens',
  }, {
    question: 'Je veux participer au Parlement Citoyen! Où dois-je m\'inscrire ?',
    summary: 'Ravi que vous soyez si enthousiaste ! Mais malheureusement, il n’est pas possible de s’inscrire. Afin garantir l’impartialité du Parlement, il est impératif qu’il soit constitué d\'un échantillon représentatif de la population de notre pays. Les membres seront tirés au sort parmi l’ensemble de la population (en tenant compte de critères démographiques tels que le sexe, l\'âge, le niveau d\'éducation, etc.)',
    answer: '',
    tags: ['tirage au sort', 'participer'],
    slug: 'je-veux-participer',
  }, {
    question: 'Je veux participer à la campagne ! Que puis-je faire ?',
    summary: 'Merci ! N\'hésite pas à parler de ce projet avec tes amis, tes collègues, ta famille. Partage, like et retweete nos messages et vidéos sur les réseaux sociaux. Sur ce site, il te sera également possible d\'adresser des tweets et d\'envoyer des emails aux hommes politiques de ton choix. Si tu penses pouvoir nous soutenir d\'une autre manière, envoie un email à l\'adresse info@thecitizensparliament.be.',
    answer: '',
    tags: ['organisation', 'participation', 'campagne'],
    slug: 'que-puis-je-faire',
  }, {
    question: 'Qu\'en est-il des participants qui perturbent le processus du Parlement civil ?',
    summary: 'Bien sûr, il faut laisser la place pour aux divergences d’opinion dans un Parlement Citoyen. Néanmoins, les facilitateurs présents veillent à ce que le comportement individuel n\'interfère pas avec l\'ensemble du processus collectif. Les membres reçoivent également une formation au départ pour apprendre à parler et à écouter en groupe. ',
    answer: '',
    tags: ['parlement', 'facilitation', 'formation'],
    slug: 'participants-qui-perturbent',
  }, {
    question: 'Puis-je donner mon avis si je ne suis pas tiré.e au sort?',
    summary: 'Des expériences ont déjà été menées dans d\'autres pays sur les contributions possibles à un parlement citoyen. Un site web public pourrait être un bon moyen pour chacun de proposer des idées et de modérer les discussions. Bien entendu, il faut veiller à ce qu\'une telle plate-forme ne souffre pas des mêmes maux que de nombreux réseaux sociaux, où l’on assiste souvent à une bataille d’opinions peu éclairées. Et, bien sûr, la représentativité du Parlement Citoyen doit être garantie : tout le monde n\'est pas à l’aise avec les réseaux sociaux.',
    answer: '',
    tags: ['démocratie', 'contribution', 'en ligne', 'forum'],
    slug: 'puis-je-donner-mon-avis-si-je-ne-suis-pas-tiree-au-sort',
  }, {
    question: 'En fin de compte, ce ne sont pas les lobbies qui vont imposer leur agenda? Ou bien le gouvernement?',
    summary: 'Les citoyens tirés au sort ont beaucoup plus difficiles à influencer par le biais du lobbying que les politiciens élus. Il est de la plus haute importance pour la légitimité du Parlement Citoyen qu\'il fonctionne indépendamment de tout acteur politique, économique ou social. Le gouvernement fédéral met en place et finance le processus, mais ne joue aucun rôle dans l\'organisation du processus de délibération, la sélection du panel d\'experts ou la supervision. Par souci de transparence, cela s\'applique également, bien entendu, aux citoyens qui se trouvent derrière cette proposition. Un groupe de coordination (professionnel), un conseil consultatif, une équipe de facilitation, un comité juridique et un groupe de suivi assurent ensemble la transparence publique, l\'indépendance politique et la légitimité démocratique du Parlement Citoyen.',
    answer: '',
    tags: ['démocratie', 'lobbies', 'partisan', 'indépendance', 'légitimité'],
    slug: 'ce-ne-sont-pas-les-lobbies-qui-vont-imposer-leur-agenda',
  }, {
    question: 'Pourquoi parlez-vous de la "crise écologique" ? Vous voulez dire "climatique", n\'est-ce pas ?',
    summary: 'Non, c’est bien ce que nous voulons dire. Malheureusement, nous ne pouvons pas limiter la perspective au réchauffement climatique. Il existe de multiples limites planétaires, que nous avons déjà franchies ou que nous sommes sur le point de franchir, ce qui va entraîner une profonde perturbation des écosystèmes vitaux. Les aspects suivants sont concernés: (1) le réchauffement climatique, (2) la perte de biodiversité, (3) le cycle de l\'azote et du phosphore, (4) le trou dans la couche d\'ozone, (5) l\'acidification des océans, (6) la pénurie d\'eau, (7) l\'utilisation des sols, (8) la pollution chimique, (9) les aérosols dans l\'atmosphère. Toute administration politique du XXIe siècle digne de ce nom devrait prendre ces limites au sérieux.',
    answer: '',
    tags: ['crise écologique', 'climat', 'biodiversité', 'pollution'],
    slug: 'pourquoi-parlez-vous-de-la-crise-ecologique',
  }, {
    question: 'L’urgence écologique n’est elle pas exagérée?',
    summary: 'Si seulement c\'était vrai ! Malheureusement, le consensus scientifique est assez alarmant. Trop peu de citoyens (et d\'hommes politiques) connaissent la différence entre un réchauffement de 1,5 ou 2 °C. Après tout, qui prend la peine de lire ces longs rapports scientifiques ? Une différence d\'un demi degré semble minime mais elle aggravera l’élévation du niveau de la mer, les inondations, les incendies, les sécheresses, la désertification, les morts dues aux vagues de chaleur, les pénuries d’eau et de nourriture. Tout cela aura un impact énorme sur la santé publique, l\'économie, la géopolitique, les migrations, etc. En plus du réchauffement climatique, il y a aussi la pollution, une perte catastrophique de biodiversité, l\'acidification de nos océans, etc. Dans de nombreuses régions du monde, certaines populations voient déjà leur habitat détruit. Jusqu\'à présent, notre pays a été épargné des conséquences les plus graves. Pourtant, même chez nous, les récoltes sont en péril en raison du manque d\'eau et d’insectes pollinisateurs. L\'élévation du niveau de la mer menace nos villes côtières. Beaucoup d\'entre nous vont mourir à cause des vagues de chaleur et de la pollution de l\'air. Cela peut sembler alarmiste, mais la situation est réellement alarmante. Lisez vous-même les rapports du GIEC et du IPBES.',
    answer: '',
    tags: ['crise écologique', 'science', 'biodiversité', 'pollution', 'GIEC', 'IPBES'],
    slug: 'lurgence-ecologique-nest-elle-pas-exageree',
  }, {
    question: 'Ce que fait un petit pays comme la Belgique n\'a aucune importance, n\'est-ce pas ?',
    summary: 'Nous pensons que oui. Bien sûr, la crise écologique est un problème mondial et beaucoup d\'instruments politiques pour faire face à cette crise sont situés au niveau de l\'Union européenne plutôt qu\'à celui de la Belgique. Bien que de nombreuses propositions soient en cours d\'élaboration pour un Parlement européen citoyen, il nous semble important de prendre les mesures administratives nécessaires en Belgique également. L’heures n’est pas aux petit pas, nous aurions plutôt besoin des bottes de sept lieues. Les représentants politiques aux différents niveaux ne peuvent plus se permettre d\'attendre chacun que l’autre bouge. Tout le monde doit mettre la main à la pâte. En plus, malgré sa petite taille, l\'impact de notre pays n\'est pas négligeable: la Belgique a la cinquième plus grande empreinte écologique au monde.',
    answer: '',
    tags: ['crise écologique', 'écologie', 'innovation', 'science'],
    slug: 'ce-que-fait-un-petit-pays-comme-la-belgique-na-aucune-importance',
  }, {
    question: 'Quelle est votre position sur... ?',
    summary: 'Bien que les citoyens à l\'origine de cette proposition aient chacun leurs préférences idéologiques, nous ne prenons pas position sur des questions politiques concrètes. Nous ne faisons que défendre la valeur d\'un Parlement Citoyen, et nous appelons le monde politique à prendre au sérieux le consensus scientifique autour de la crise écologique et à mettre en œuvre des politiques qui respectent les limites planétaires. Nous considérons cette initiative comme une opportunité unique de faire le lien entre innovation démocratique et politique environnementale. Mais les propositions politiques concrètes doivent être élaborées par les membres tirés au sort du Parlement Citoyen, et non par nous.',
    answer: '',
    tags: ['organisation', 'partisan', 'politique', 'idéologie', 'science'],
    slug: 'quelle-est-votre-position-sur',
  }, {
    question: 'Et si les citoyens tirés au sort ont aussi leurs propres intérêts ?',
    summary: 'Il est clair que ce sera certainement le cas, et il n\'y a rien de mal à cela. La représentativité du Parlement Citoyen garantit toutefois la diversité des intérêts représentés. Et aussi que les intérêts des grands acteurs aient moins d\'impact. Les citoyens tirés au sort sont moins sensibles au lobbying que les politiciens. De plus, l\'expérience et les recherches montrent qu\'une fois que les membres d\'un parlement citoyen sont confrontés aux intérêts de beaucoup d\'autres acteurs, ils mettent leurs propres intérêts en perspective et deviennent plus conscients de l\'intérêt général.',
    answer: '',
    tags: ['pratique', 'lobbying', 'partisan'],
    slug: 'et-si-les-citoyens-tires-au-sort-ont-aussi-leurs-propres-interets',
  }, {
    question: 'Pourquoi ce Parlement Citoyen doit-il être temporaire et ponctuel?',
    summary: 'C’est une bonne question. Dans les cantons de l\'Est de notre pays, il existe déjà un organe permanent de participation citoyenne, le "Dialogue des citoyens". Toutefois, nous concentrons notre campagne sur une initiative ponctuelle. Nous voulons que cette initiative devienne une réalité et nous craignons que la demande d\'un organe plus permanent soit politiquement irréaliste. Bien entendu, nous n’allons pas  "résoudre" tous les problèmes liés à l\'urgence écologique, même si les travaux du Parlement Citoyen se dérouleront pendant un an. Néanmoins, nous pensons que d\'énormes progrès peuvent être accomplis. L’idée d’un organe institutionnel permanent ou d’une série de parlements citoyens axés sur des thèmes précis vaut certainement la peine d\'être explorés, mais elle dépasse le cadre de cette campagne.',
    answer: '',
    tags: ['démocratie', 'campagne'],
    slug: 'pourquoi-ce-parlement-doit-il-etre-temporaire',
  }, {
    question: 'Nous avons déjà un plan national pour l\'énergie et le climat, n\'est-ce pas ?',
    summary: 'C\'est exact;après de longues négociations, la Belgique a soumis son <a target="_blank" href="https://www.plannationalenergieclimat.be/fr/le-pnec-c-est-quoi">Plan national énergie et climat</a> à la Commission européenne à la dernière minute. Il s\'agit de la compilation des plans individuels des trois régions. Ensemble, ils visent à réduire les émissions de CO2 de 35 % par rapport à 1990. Aujourd\'hui, moins de deux ans plus tard, l\'Europe a placé la barre beaucoup plus haut : 60 % de réduction. Les efforts les plus faciles ont déjà été faits. En deux ans, les perspectives ne se sont pas améliorées, au contraire. Notre nouveau gouvernement promet de s\'en tenir à la sortie du nucléaire, qui sera compensée par cinq nouvelles centrales au gaz émettant <a target="_blank" href="https://www.energyville.be/nieuws-events/energyville-lanceert-aanvullende-systeemscenarios-voor-elektriciteitsvoorziening">25 millions de tonnes de CO2 supplémentaires</a>. Ce sera donc un équilibre difficile, pour lequel le gouvernement devra faire des choix difficiles. Rejoignez-nous plutôt à la table des négociations. Au final, ce plan ne traite que de l\'énergie et des émissions de CO2, tout en ignorant les autres défis écologiques : perte de biodiversité, pollution,...',
    answer: '',
    tags: ['crise écologique', 'démocratie', 'science', 'PNEC'],
    slug: 'nous-avons-deja-un-plan-national-pour-lenergie-et-le-climat',
  }, {
    question: 'Quelle garantie y a-t-il que les propositions seront mises en œuvre ?',
    summary: 'Bonne question. En France, avant le lancement de la Convention Citoyenne pour le Climat, le Président Macron a promis que chaque proposition citoyenne (1) serait mise en œuvre par décret présidentiel, soit (2) votée au parlement, soit (3) soumise à la population par référendum. Bien sûr, les hommes politiques ne tiennent pas toujours leurs promesses, et cela vaut aussi pour la France. Le Président a d\'abord promis de mettre en œuvre 146 des 149 propositions, mais cela s\'est vite dilué. Les membres de la Convention ont donc formé le groupe de pression: Les 150. Le pouvoir d\'un parlement citoyen est également relatif dans notre pays : la constitution belge empêche les citoyens non élus (mais tirés au sort) d\'exercer le pouvoir législatif. Néanmoins, nous proposons plus qu\'un simple organe consultatif. Le Parlement Citoyen aura un impact dans la mesure où chacune de ses propositions politiques sera mise en œuvre par le(s) gouvernement(s) compétent(s) ou soumise au(x) parlement(s) compétent(s) pour un vote (avec des justifications approfondies et accessibles au public à chaque fois que des propositions sont rejetées).',
    answer: '',
    tags: ['démocratie', 'pouvoir', 'séance de parlotte', 'XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX'],
    slug: 'quelle-garantie-y-a-t-il-que-les-propositions-seront-mises-en-oeuvre',
  }, {
    question: 'Pourquoi pas un référendum ?',
    summary: 'De nombreux exemples ont déjà montré à quel point les référendums peuvent être polarisants et contre-productifs. Ils réduisent la complexité d\'un domaine politique spécifique à une question simple et trompeuse à laquelle les citoyens ne peuvent répondre que par "oui" ou "non". Les référendums sont diamétralement opposés à la démocratie délibérative, qui repose sur l’information approfondie d\'un groupe de citoyens très divers depuis différents angles et une délibération facilitée. L\'option d\'un préférendum - dans laquelle la population serait mieux informée et se verrait présenter une large liste de propositions auxquelles elle peut répondre dans un spectre entre "d\'accord" et "en désaccord" - vaut certainement la peine d\'être explorée.',
    answer: '',
    tags: ['démocratie', 'complexité', 'polarisation'],
    slug: 'pourquoi-pas-un-referendum',
  }, {
    question: 'Et si je ne veux pas participer ?',
    summary: 'Personne n\'est obligé de participer. Vous êtes un des citoyens tirés au sort mais cela ne vous inspire pas? Vous avez d\'autres préoccupations ou vous ne pouvez pas participer pendant les périodes demandées ? Pas de problème! Nous préconisons toutefois que tout soit fait pour que la participation de chacun soit pratiquement possible : une indemnité journalière équitable, des services de garde d\'enfants ou d\'autres aides pour les proches, une indemnité de transport, un bon encadrement, ...  Mais êtes-vous sûr de vouloir rater cette occasion unique ? Les participants à la Convention Citoyenne pour le Climat française <a target="_blank" href="https://www.conventioncitoyennepourleclimat.fr/portraits-citoyens/">ne l\'ont pas regretté</a> !',
    answer: '',
    tags: ['pratique', 'participation', 'tirage au sort'],
    slug: 'et-si-je-ne-veux-pas-participer',
  }, {
    question: 'Les syndicats, et la société civile en général, n’ont-ils plus rien à dire ?',
    summary: 'Outre la représentation par des hommes et femmes politiques élu.e.s, d\'autres formes de représentation restent de la plus haute importance. La voix des syndicats et des autres organisations de la société civile peut être entendue dès les premières étapes du processus de délibération, aux côtés de celle des climatologues, des écologistes, des juristes, des journalistes, des militants, des architectes, des représentants des entreprises, des secteurs de la construction, de l\'agriculture, de l\'énergie, des transports et de la mobilité, des ministères, des fonctionnaires, etc. Lors des premières sessions du Parlement Citoyen, un large éventail d\'experts et de parties prenantes informent les citoyens tirés au sort. Toutefois, le rôle de loin le plus important pour les syndicats et les organisations de la société civile sera joué après la conclusion des travaux du Parlement Citoyen. Ils doivent s\'assurer que les propositions du Parlement Citoyen ont un impact suffisant sur la politique réelle.',
    answer: '',
    tags: ['parlement', 'experts'],
    slug: 'les-syndicats-ont-ils-quelque-chose-a-dire',
  },
];
