import { MP } from './mp/mp';

export const members: MP[] = [
  {
      "parliament": "De Kamer",
      "name": "Anseeuw Björn",
      "party": "N-VA",
      "id": "07508",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07508.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07508&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "07508.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Aouasti Khalil",
      "party": "PS",
      "id": "07124",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07124.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07124&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Anderlecht",
      "language": "Frans",
      "localImg": "07124.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Arens Josy",
      "party": "cdH",
      "email": "josy.arens@lachambre.be",
      "id": "00866",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00866.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00866&lactivity=55",
      "constituency": "Luxemburg",
      "hometown": "Aarlen",
      "language": "Frans",
      "localImg": "00866.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Bayet Hugues",
      "party": "PS",
      "id": "07169",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07169.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07169&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Dinant",
      "language": "Frans",
      "localImg": "07169.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Ben Achour Malik",
      "party": "PS",
      "id": "06733",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06733.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06733&lactivity=55",
      "constituency": "Luik",
      "hometown": "Verviers",
      "language": "Frans",
      "localImg": "06733.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Bertels Jan",
      "party": "sp.a",
      "id": "06172",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06172.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06172&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Herentals",
      "language": "Nederlands",
      "localImg": "06172.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Bihet Mathieu",
      "party": "MR",
      "id": "07254",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07254.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07254&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "07254.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Bogaert Hendrik",
      "party": "CD&V",
      "email": "hendrik.bogaert@dekamer.be",
      "id": "01039",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01039.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01039&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "01039.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Bombled Christophe",
      "party": "MR",
      "id": "06934",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06934.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06934&lactivity=55",
      "constituency": "Namen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "06934.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Boukili Nabil",
      "party": "PVDA-PTB",
      "id": "07133",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07133.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07133&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Dujda (Marokko)",
      "language": "Frans",
      "localImg": "07133.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Briers Jan",
      "party": "CD&V",
      "id": "07346",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07346.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07346&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "07346.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Burton Emmanuel",
      "party": "MR",
      "email": "emmanuel.burton@lachambre.be",
      "id": "O1057",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/O1057.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=O1057&lactivity=55",
      "constituency": "Waals-Brabant",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "O1057.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Bury Katleen",
      "party": "VB",
      "email": "katleen.bury@dekamer.be",
      "id": "07425",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07425.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07425&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "07425.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Buysrogge Peter",
      "party": "N-VA",
      "id": "06030",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06030.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06030&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Sint-Niklaas",
      "language": "Nederlands",
      "localImg": "06030.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Buyst Kim",
      "party": "Ecolo-Groen",
      "id": "07010",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07010.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07010&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "07010.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Calvo Kristof",
      "party": "Ecolo-Groen",
      "email": "kristof.calvo@dekamer.be",
      "id": "06128",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06128.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06128&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Rumst",
      "language": "Nederlands",
      "localImg": "06128.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Chanson Julie",
      "party": "Ecolo-Groen",
      "id": "07245",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07245.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07245&lactivity=55",
      "constituency": "Luik",
      "hometown": "Verviers",
      "language": "Frans",
      "localImg": "07245.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Cogolati Samuel",
      "party": "Ecolo-Groen",
      "email": "samuel.cogolati@huy.be",
      "id": "07244",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07244.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07244&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "07244.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Colebunders Gaby",
      "party": "PVDA-PTB",
      "id": "07271",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07271.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07271&lactivity=55",
      "constituency": "Luik",
      "hometown": "Genk",
      "language": "Frans",
      "localImg": "07271.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Creemers Barbara",
      "party": "Ecolo-Groen",
      "id": "07199",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07199.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07199&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Maaseik",
      "language": "Nederlands",
      "localImg": "07199.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Creyelman Steven",
      "party": "VB",
      "email": "steven.creyelman@vlaamsbelang.org",
      "id": "06873",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06873.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06873&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "06873.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Crombez John",
      "party": "sp.a",
      "email": "john.crombez@s-p-a.be",
      "id": "01307",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01307.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01307&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "01307.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Daems Greet",
      "party": "PVDA-PTB",
      "id": "07048",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07048.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07048&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "07048.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Dallemagne Georges",
      "party": "cdH",
      "email": "georges.dallemagne@lachambre.be",
      "id": "00951",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/00951.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00951&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Fataki (DRC)",
      "language": "Frans",
      "localImg": "00951.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "D'Amico Roberto",
      "party": "PVDA-PTB",
      "id": "07182",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07182.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07182&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "07182.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Caluwé Robby",
      "party": "Open Vld",
      "email": "info@robbydecaluwe.be",
      "id": "07358",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07358.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07358&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Lokeren",
      "language": "Nederlands",
      "localImg": "07358.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Dedecker Jean-Marie",
      "party": "ONAFH",
      "email": "jean-marie.dedecker@dekamer.be",
      "id": "00954",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/00954.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00954&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Nieuwpoort",
      "language": "Nederlands",
      "localImg": "00954.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Dedonder Ludivine",
      "party": "PS",
      "email": "ludivine.dedonder@tournai.be",
      "id": "06336",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06336.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06336&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Doornik",
      "language": "Frans",
      "localImg": "06336.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Jonge Tania",
      "party": "Open Vld",
      "email": "burgemeester@ninove.be",
      "id": "07352",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07352.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07352&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Ninove",
      "language": "Nederlands",
      "localImg": "07352.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "de Laveleye Séverine",
      "party": "Ecolo-Groen",
      "id": "07111",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07111.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07111&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "07111.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Delizée Jean-Marc",
      "party": "PS",
      "email": "jean-marc.delizee@lachambre.be",
      "id": "00746",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00746.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00746&lactivity=55",
      "constituency": "Namen",
      "hometown": "Oignies-en-Thiérache",
      "language": "Frans",
      "localImg": "00746.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Delvaux Bram",
      "party": "Open Vld",
      "id": "07419",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07419.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07419&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Tienen",
      "language": "Nederlands",
      "localImg": "07419.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Maegd Michel",
      "party": "MR",
      "id": "07122",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07122.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07122&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "07122.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Demon Franky",
      "party": "CD&V",
      "email": "franky.demon@dekamer.be",
      "id": "06805",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06805.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06805&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "06805.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Depoorter Kathleen",
      "party": "N-VA",
      "id": "07387",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07387.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07387&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "07387.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Depoortere Ortwin",
      "party": "VB",
      "email": "ortwin.depoortere@vlaamsbelang.org",
      "id": "01129",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01129.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01129&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Izegem",
      "language": "Nederlands",
      "localImg": "01129.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Depraetere Melissa",
      "party": "sp.a",
      "id": "07494",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07494.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07494&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Kortrijk",
      "language": "Nederlands",
      "localImg": "07494.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Roover Peter",
      "party": "N-VA",
      "email": "peter.deroover@dekamer.be",
      "id": "06588",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06588.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06588&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Turnhout",
      "language": "Nederlands",
      "localImg": "06588.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "De Smet François",
      "party": "DéFI",
      "email": "fdesmet@defi.eu",
      "id": "07100",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07100.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07100&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "07100.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Spiegeleer Pieter",
      "party": "VB",
      "email": "pieter.despiegeleer@dekamer.be",
      "id": "07339",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07339.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07339&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Zottegem",
      "language": "Nederlands",
      "localImg": "07339.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "De Vriendt Wouter",
      "party": "Ecolo-Groen",
      "email": "wouter.de.vriendt@dekamer.be",
      "id": "01199",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01199.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01199&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "01199.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "De Vuyst Steven",
      "party": "PVDA-PTB",
      "id": "07399",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07399.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07399&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "07399.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Dewael Patrick",
      "party": "Open Vld",
      "email": "patrick.dewael@dekamer.be",
      "id": "00124",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00124.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00124&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "00124.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "De Wit Sophie",
      "party": "N-VA",
      "email": "sophie.dewit@dekamer.be",
      "id": "06141",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06141.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06141&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Deurne",
      "language": "Nederlands",
      "localImg": "06141.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Dewulf Nathalie",
      "party": "VB",
      "email": "nathalie.dewulf@vlaamsbelang.org",
      "id": "07477",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07477.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07477&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Izegem",
      "language": "Nederlands",
      "localImg": "07477.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "D'Haese Christoph",
      "party": "N-VA",
      "email": "christoph.dhaese@dekamer.be",
      "id": "06907",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06907.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06907&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Aalst",
      "language": "Nederlands",
      "localImg": "06907.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Dierick Leen",
      "party": "CD&V",
      "email": "leen.dierick@dekamer.be",
      "id": "01201",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01201.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01201&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "01201.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Dillen Marijke",
      "party": "VB",
      "email": "marijke.dillen@outlook.be",
      "id": "00636",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/00636.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00636&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Mortsel",
      "language": "Nederlands",
      "localImg": "00636.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Dock Magali",
      "party": "MR",
      "id": "07255",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/7255.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07255&lactivity=55",
      "constituency": "Luik",
      "hometown": "Hoei",
      "language": "Frans",
      "localImg": "anonymous.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Donné Joy",
      "party": "N-VA",
      "id": "07207",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07207.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07207&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Hasselt",
      "language": "Nederlands",
      "localImg": "07207.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Farih Nawal",
      "party": "CD&V",
      "id": "07192",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07192.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07192&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Sarcelles (Frankrijk)",
      "language": "Nederlands",
      "localImg": "07192.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Flahaut André",
      "party": "PS",
      "email": "andre.flahaut@lachambre.be",
      "id": "00761",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00761.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00761&lactivity=55",
      "constituency": "Waals-Brabant",
      "hometown": "Walhain",
      "language": "Frans",
      "localImg": "00761.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Fonck Catherine",
      "party": "cdH",
      "email": "catherine.fonck@lachambre.be",
      "id": "01076",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01076.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01076&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Ciney",
      "language": "Frans",
      "localImg": "01076.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Francken Theo",
      "party": "N-VA",
      "email": "theo.francken@dekamer.be",
      "id": "04666",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/04666.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=04666&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Lubbeek",
      "language": "Nederlands",
      "localImg": "04666.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Freilich Michael",
      "party": "N-VA",
      "email": "michael.freilich@n-va.be",
      "id": "07022",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07022.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07022&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "07022.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Friart Benoît",
      "party": "MR",
      "email": "benoit.friart@lachambre.be",
      "id": "06663",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06663.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06663&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "06663.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Gabriëls Katja",
      "party": "Open Vld",
      "email": "katja.gabriels@dekamer.be",
      "id": "06885",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06885.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06885&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "06885.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Galant Isabelle",
      "party": "MR",
      "email": "isabelle.galant@lachambre.be",
      "id": "06665",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06665.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06665&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Aat",
      "language": "Frans",
      "localImg": "06665.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Gijbels Frieda",
      "party": "N-VA",
      "id": "06499",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06499.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06499&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Bree",
      "language": "Nederlands",
      "localImg": "06499.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Gilissen Erik",
      "party": "VB",
      "email": "erik.gilissen@dekamer.be",
      "id": "07228",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07228.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07228&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "07228.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Gilkinet Georges",
      "party": "Ecolo-Groen",
      "email": "georges.gilkinet@lachambre.be",
      "id": "01205",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01205.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01205&lactivity=55",
      "constituency": "Namen",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "01205.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Gilson Nathalie",
      "party": "MR",
      "id": "O599",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/O599.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=O599&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "O599.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Goblet Marc",
      "party": "PS",
      "email": "deputegoblet@outlook.com",
      "id": "07261",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07261.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07261&lactivity=55",
      "constituency": "Luik",
      "hometown": "Herve",
      "language": "Frans",
      "localImg": "07261.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Hanus Mélissa",
      "party": "PS",
      "id": "07295",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07295.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07295&lactivity=55",
      "constituency": "Luxemburg",
      "hometown": "Aarlen",
      "language": "Frans",
      "localImg": "07295.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Hedebouw Raoul",
      "party": "PVDA-PTB",
      "email": "raoul.hedebouw@lachambre.be",
      "id": "06759",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06759.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06759&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "06759.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Hennuy Laurence",
      "party": "Ecolo-Groen",
      "id": "06309",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06309.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06309&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Gosselies",
      "language": "Frans",
      "localImg": "06309.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Houtmeyers Katrien",
      "party": "N-VA",
      "id": "07417",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07417.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07417&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "07417.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Ingels Yngvild",
      "party": "N-VA",
      "id": "07481",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07481.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07481&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Duinkerke-Noord (Frankrijk)",
      "language": "Nederlands",
      "localImg": "07481.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Jadin Kattrin",
      "party": "MR",
      "id": "01207",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01207.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01207&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "01207.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Jiroflée Karin",
      "party": "sp.a",
      "id": "01070",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01070.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01070&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "01070.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Khattabi Zakia",
      "party": "Ecolo-Groen",
      "email": "zakia.khattabi@ecolo.be",
      "id": "01310",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01310.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01310&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sint-Joost-ten-Node",
      "language": "Frans",
      "localImg": "01310.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Kir Emir",
      "party": "ONAFH",
      "email": "emir.kir@lachambre.be",
      "id": "06645",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06645.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06645&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "06645.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Kitir Meryame",
      "party": "sp.a",
      "email": "meryame@kitir.be ",
      "id": "01209",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01209.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01209&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Maasmechelen",
      "language": "Nederlands",
      "localImg": "01209.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Laaouej Ahmed",
      "party": "PS",
      "email": "ahmed.laaouej@lachambre.be",
      "id": "06461",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06461.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06461&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "06461.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Lachaert Egbert",
      "party": "Open Vld",
      "email": "egbert.lachaert@dekamer.be",
      "id": "06884",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06884.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06884&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "06884.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Lacroix Christophe",
      "party": "PS",
      "email": "christophe.lacroix@lachambre.be",
      "id": "06389",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06389.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06389&lactivity=55",
      "constituency": "Luik",
      "hometown": "Hoei",
      "language": "Frans",
      "localImg": "06389.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Lanjri Nahima",
      "party": "CD&V",
      "id": "01042",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01042.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01042&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Borgerhout",
      "language": "Nederlands",
      "localImg": "01042.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Leroy Marie-Colline",
      "party": "Ecolo-Groen",
      "email": "marie-colline.leroy@ecolo.be",
      "id": "07153",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07153.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07153&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Baudour",
      "language": "Frans",
      "localImg": "07153.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Leysen Christian",
      "party": "Open Vld",
      "id": "07034",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07034.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07034&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "07034.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Liekens Goedele",
      "party": "Open Vld",
      "id": "07448",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07448.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07448&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Aarschot",
      "language": "Nederlands",
      "localImg": "07448.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Loones Sander",
      "party": "N-VA",
      "id": "06985",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06985.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06985&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Veurne",
      "language": "Nederlands",
      "localImg": "06985.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Mahdi Sammy",
      "party": "CD&V",
      "id": "07407",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07407.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07407&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Elsene",
      "language": "Nederlands",
      "localImg": "07407.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Matheï Steven",
      "party": "CD&V",
      "id": "07193",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07193.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07193&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Bree",
      "language": "Nederlands",
      "localImg": "07193.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Matz Vanessa",
      "party": "cdH",
      "email": "vanessa.matz@lachambre.be",
      "id": "01281",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01281.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01281&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "01281.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Merckx Sofie",
      "party": "PVDA-PTB",
      "email": "sofie.merckx@ptb.be",
      "id": "07181",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07181.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07181&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Wilrijk",
      "language": "Frans",
      "localImg": "07181.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Mertens Peter",
      "party": "PVDA-PTB",
      "id": "07047",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07047.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07047&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "07047.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Metsu Koen",
      "party": "N-VA",
      "email": "koen.metsu@dekamer.be",
      "id": "06591",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06591.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06591&lactivity=55",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "localImg": "06591.gif",
      "hometown": "Edegem"
  },
  {
      "parliament": "De Kamer",
      "name": "Moscufo Nadia",
      "party": "PVDA-PTB",
      "email": "nadia.moscufo@ptb.be",
      "id": "07270",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07270.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07270&lactivity=55",
      "constituency": "Luik",
      "hometown": "Hermalle-sous-Argenteau",
      "language": "Frans",
      "localImg": "07270.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Moutquin Simon",
      "party": "Ecolo-Groen",
      "id": "06534",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06534.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06534&lactivity=55",
      "constituency": "Waals-Brabant",
      "hometown": "Ottignies-Louvain-la-Neuve",
      "language": "Frans",
      "localImg": "06534.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Özen Özlem",
      "party": "PS",
      "email": "ozlem.ozen@lachambre.be",
      "id": "06326",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06326.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06326&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "06326.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Pas Barbara",
      "party": "VB",
      "email": "barbara.pas@vlaamsbelang.org",
      "id": "01236",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01236.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01236&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Temse",
      "language": "Nederlands",
      "localImg": "01236.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Piedboeuf Benoît",
      "party": "MR",
      "email": "benoit.piedboeuf@lachambre.be",
      "id": "06423",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06423.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06423&lactivity=55",
      "constituency": "Luxemburg",
      "hometown": "Musienene (DRC)",
      "language": "Frans",
      "localImg": "06423.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Pivin Philippe",
      "party": "MR",
      "email": "philippe@pivin.be",
      "id": "06618",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06618.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06618&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sint-Agatha-Berchem",
      "language": "Frans",
      "localImg": "06618.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Ponthier Annick",
      "party": "VB",
      "email": "annick.ponthier@dekamer.be",
      "id": "01292",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/01292.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01292&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "01292.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Prévot Maxime",
      "party": "cdH",
      "email": "maxime.prevot@lachambre.be",
      "id": "01216",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/01216.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01216&lactivity=55",
      "constituency": "Namen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "01216.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Prévot Patrick",
      "party": "PS",
      "id": "06967",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06967.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06967&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "06967.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Raskin Wouter",
      "party": "N-VA",
      "id": "06498",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06498.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06498&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "06498.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Ravyts Kurt",
      "party": "VB",
      "email": "kurt.ravyts@vlaamsbelang.org",
      "id": "07485",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07485.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07485&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "07485.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Reuter Florence",
      "party": "MR",
      "email": "florence.reuter@waterloo.be",
      "id": "01217",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/01217.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01217&lactivity=55",
      "constituency": "Waals-Brabant",
      "hometown": "Malmédy",
      "language": "Frans",
      "localImg": "01217.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Rigot Hervé",
      "party": "PS",
      "id": "07263",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07263.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07263&lactivity=55",
      "constituency": "Luik",
      "language": "Frans",
      "localImg": "07263.jpg",
      "hometown": "Waremme"
  },
  {
      "parliament": "De Kamer",
      "name": "Roggeman Tomas",
      "party": "N-VA",
      "id": "07369",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07369.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07369&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "07369.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Rohonyi Sophie",
      "party": "DéFI",
      "email": "srohonyi@defi.eu",
      "id": "07102",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07102.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07102&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Eigenbrakel",
      "language": "Frans",
      "localImg": "07102.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Safai Darya",
      "party": "N-VA",
      "id": "07416",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07416.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07416&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Teheran (Iran)",
      "language": "Nederlands",
      "localImg": "07416.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Samyn Ellen",
      "party": "VB",
      "email": "ellen.samyn@dekamer.be",
      "id": "07076",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07076.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07076&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Roeselare",
      "language": "Nederlands",
      "localImg": "07076.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Schlitz Sarah",
      "party": "Ecolo-Groen",
      "email": "sarah.schlitz@ecolo.be",
      "id": "06722",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06722.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06722&lactivity=55",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "06722.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Scourneau Vincent",
      "party": "MR",
      "id": "06287",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/6287.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06287&lactivity=55",
      "constituency": "Waals Brabant",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "anonymous.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Segers Ben",
      "party": "sp.a",
      "id": "07063",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/07063.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07063&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "07063.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Senesael Daniel",
      "party": "PS",
      "email": "daniel.senesael@lachambre.be",
      "id": "06682",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06682.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06682&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Doornik",
      "language": "Frans",
      "localImg": "06682.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Slegers Bercy",
      "party": "CD&V",
      "email": "bercy.slegers@dekamer.be",
      "id": "04872",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/04872.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=04872&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Poperinge",
      "language": "Nederlands",
      "localImg": "04872.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Sneppe Dominiek",
      "party": "VB ",
      "email": "dominiek.sneppe@dekamer.be",
      "id": "O1330",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/O1330.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=O1330&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "O1330.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Soors Jessika",
      "party": "Ecolo-Groen",
      "id": "07410",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07410.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07410&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Jette",
      "language": "Nederlands",
      "localImg": "07410.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Spooren Jan",
      "party": "N-VA",
      "email": "jan.spooren@n-va.be",
      "id": "06841",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06841.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06841&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Herk-de-Stad",
      "language": "Nederlands",
      "localImg": "06841.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Taquin Caroline",
      "party": "MR",
      "email": "caroline.taquin@lachambre.be",
      "id": "07162",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07162.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07162&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "07162.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Thémont Sophie",
      "party": "PS",
      "email": "deputee@sophiethemont.be",
      "id": "07262",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07262.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07262&lactivity=55",
      "constituency": "Luik",
      "hometown": "Aat",
      "language": "Frans",
      "localImg": "07262.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Thibaut Cécile",
      "party": "Ecolo-Groen",
      "email": "cecile.thibaut@ecolo.be",
      "id": "01309",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/01309.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01309&lactivity=55",
      "constituency": "Luxemburg",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "01309.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Thiébaut Eric",
      "party": "PS",
      "email": "eric.thiebaut@lachambre.be",
      "id": "01222",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01222.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01222&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "01222.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Tillieux Eliane",
      "party": "PS",
      "id": "O2619",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/O2619.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=O2619&lactivity=55",
      "constituency": "Namen",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "O2619.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Tison Philippe",
      "party": "PS",
      "id": "07171",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07171.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07171&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Lobbes",
      "language": "Frans",
      "localImg": "07171.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Troosters Frank",
      "party": "VB",
      "email": "frank.troosters@dekamer.be",
      "id": "07227",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07227.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07227&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Hasselt",
      "language": "Nederlands",
      "localImg": "07227.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Vanbesien Dieter",
      "party": "Ecolo-Groen",
      "id": "07411",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07411.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07411&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Bonheiden",
      "language": "Nederlands",
      "localImg": "07411.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Bossuyt Anneleen",
      "party": "N-VA",
      "id": "07354",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07354.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07354&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "07354.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Camp Yoleen",
      "party": "N-VA",
      "email": "yoleen.vancamp@dekamer.be",
      "id": "06590",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06590.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06590&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "06590.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van den Bergh Jef",
      "party": "CD&V",
      "id": "01131",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01131.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01131&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Essen",
      "language": "Nederlands",
      "localImg": "01131.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Vandenbroucke Joris",
      "party": "sp.a",
      "id": "07366",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07366.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07366&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "07366.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Vanden Burre Gilles",
      "party": "Ecolo-Groen",
      "email": "gilles.vandenburre@lachambre.be",
      "id": "06638",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06638.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06638&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "06638.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Vandenput Tim",
      "party": "Open Vld",
      "email": "tim.vandenput@dekamer.be",
      "id": "06823",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06823.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06823&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Ukkel",
      "language": "Nederlands",
      "localImg": "06823.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van der Donckt Wim",
      "party": "N-VA",
      "id": "06595",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06595.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06595&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Oudenaarde",
      "language": "Nederlands",
      "localImg": "06595.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van der Straeten Tinne",
      "party": "Ecolo-Groen",
      "id": "01226",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/01226.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01226&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Zoersel",
      "language": "Nederlands",
      "localImg": "01226.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Grieken Tom",
      "party": "VB",
      "email": "tom.vangrieken@vlaamsbelang.org",
      "id": "07075",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07075.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07075&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "07075.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Hecke Stefaan",
      "party": "Ecolo-Groen",
      "email": "stefaan.vanhecke@dekamer.be",
      "id": "01227",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/01227.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=01227&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "01227.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Hees Marco",
      "party": "PVDA-PTB",
      "email": "marco.vanhees@lachambre.be",
      "id": "06701",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06701.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06701&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Sint-Agatha-Berchem",
      "language": "Frans",
      "localImg": "06701.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Hoof Els",
      "party": "CD&V",
      "email": "els.vanhoof@dekamer.be",
      "id": "06852",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/6852.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06852&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "anonymous.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Langenhove Dries",
      "party": "VB",
      "email": "dries.vanlangenhove@dekamer.be",
      "id": "07424",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07424.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07424&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "07424.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Lommel Reccino",
      "party": "VB",
      "email": "reccino.vanlommel@vlaamsbelang.org",
      "id": "07077",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07077.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07077&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Turnhout",
      "language": "Nederlands",
      "localImg": "07077.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Peel Valerie",
      "party": "N-VA",
      "email": "valerie.vanpeel@dekamer.be",
      "id": "06589",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06589.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06589&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Ekeren",
      "language": "Nederlands",
      "localImg": "06589.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Quickenborne Vincent",
      "party": "Open Vld",
      "email": "vincentvq@mac.com",
      "id": "00972",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00972.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00972&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "00972.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Vanrobaeys Anja",
      "party": "sp.a",
      "id": "06897",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/06897.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06897&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Lüdenscheid (Duitsland)",
      "language": "Nederlands",
      "localImg": "06897.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Van Vaerenbergh Kristien",
      "party": "N-VA",
      "email": "kristien.vanvaerenbergh@dekamer.be",
      "id": "06230",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06230.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06230&lactivity=55",
      "constituency": "Vlaams-Brabant",
      "hometown": "Halle",
      "language": "Nederlands",
      "localImg": "06230.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Verduyckt Kris",
      "party": "sp.a",
      "id": "07219",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07219.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07219&lactivity=55",
      "constituency": "Limburg",
      "hometown": "Lommel",
      "language": "Nederlands",
      "localImg": "07219.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Verhaert Marianne",
      "party": "Open Vld",
      "id": "07035",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07035.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07035&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "07035.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Verhelst Kathleen",
      "party": "Open Vld",
      "email": "kathleen-verhelst@kathleen-verhelst.be",
      "id": "07502",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07502.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07502&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Roeselare",
      "language": "Nederlands",
      "localImg": "07502.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Verherstraeten Servais",
      "party": "CD&V",
      "email": "servais.verherstraeten@dekamer.be",
      "id": "00826",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/00826.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=00826&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Balen",
      "language": "Nederlands",
      "localImg": "00826.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Vermeersch Wouter",
      "party": "VB",
      "email": "wouter.vermeersch@vlaamsbelang.org",
      "id": "07487",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07487.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07487&lactivity=55",
      "constituency": "West-Vlaanderen",
      "hometown": "Kortrijk",
      "language": "Nederlands",
      "localImg": "07487.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Verreyt Hans",
      "party": "VB",
      "email": "hans.verreyt@vlaamsbelang.org",
      "id": "07078",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07078.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07078&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "07078.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Vicaire Albert",
      "party": "Ecolo-Groen",
      "email": "albert.vicaire@ecolo.be",
      "id": "07154",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07154.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07154&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "07154.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Vindevoghel Maria",
      "party": "PVDA-PTB",
      "id": "07137",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07137.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07137&lactivity=55",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Waregem",
      "language": "Nederlands",
      "localImg": "07137.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Warmoes Thierry",
      "party": "PVDA-PTB",
      "email": "thierry.warmoes@ptb.be",
      "id": "07322",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07322.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07322&lactivity=55",
      "constituency": "Namen",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "07322.jpg"
  },
  {
      "parliament": "De Kamer",
      "name": "Willaert Evita",
      "party": "Ecolo-Groen",
      "email": "evita.willaert@groen.be",
      "id": "06861",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06861.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06861&lactivity=55",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "06861.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Wollants Bert",
      "party": "N-VA",
      "email": "bert.wollants@dekamer.be",
      "id": "06147",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/06147.gif",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=06147&lactivity=55",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "06147.gif"
  },
  {
      "parliament": "De Kamer",
      "name": "Zanchetta Laurence",
      "party": "PS",
      "email": "laurencezanchetta@hotmail.com",
      "id": "07170",
      "image": "https://www.dekamer.be/site/wwwroot/images/cv/ksegna_55/07170.jpg",
      "profile": "https://www.dekamer.be/kvvcr/showpage.cfm?section=/depute&language=nl&cfm=cvview54.cfm?key=07170&lactivity=55",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "07170.jpg"
  }
]
