export const NL_SUBJECTS = [
  'Richt een burgerparlement om te ontkomen aan ecologische rampen',
  'Laat burgers zelf maatregelen kiezen tegen ecologische crisissen!',
  'De oplossing voor de ecologische crisissen: een burgerparlement',
  'Laat burgers de hete ecologische aardappels voor u uit het vuur halen',
  'Nu of nooit: de oplossing voor de klimaat- en andere ecologische crisissen',
  'De toekomst van onze generatie, en duizenden na mij, ligt in uw handen',
  'Alternatief voor de partijpolitiek: het burgerparlement',
];

export const NL_BODIES = ['Beste vertegenwoordiger,\n\n' +
'Het wordt steeds duidelijker. De ecologische crisissen die de komende decennia op ons af komen zullen niet mals zijn. De klimaatverandering is vandaag al een feit. Dat België al 2,5 graden opgewarmd is, hebben we afgelopen twee zomers zelf ondervonden. Door de aanhoudende droogte zitten onze boeren met de handen in het haar. En wij in welvarende landen hebben dan nog het minst te vrezen. Maar klimaatverandering is lang niet de enige onrustwekkende ramp die voor de deur staat. WWF rapporteerde zopas in haar \'Living Planet report\' dat 2/3 van de dierenpopulaties verdwenen is in de afgelopen 50 jaar. En de VN rapporteerden zonet dat geen enkel van de 20 doelen rond biodiversiteit volledig bereikt werd. Om het tij echt te keren zijn drastische maatregelen nodig, stellen ze.\n\n' +
'Ook Europa erkent de problemen en legt haar deelstaten ingrijpende doelstellingen op. Europa zal tegen 2030 haar uitstoot met 55% verminderen ten opzichte van 1990. Ook België en Vlaanderen zullen hierin moeten meegaan. Hoe gaan we dat voor mekaar krijgen?\n\n' +
'Het laaghangend fruit is al lang geplukt. En na ellenlange onderhandelingen slaagde België er niet in een ambitieuzer doel dan een 35% reductie voor te leggen aan Europa (en het is nog niet zeker of we dat halen). Ik begrijp dat het onmogelijk wordt om nog hogere reducties waar te maken - zonder stringente maatregelen. En ik begrijp ook dat geen enkele partij deze durft voor te stellen, uit angst voor stemmenverlies. Ziedaar de patstelling.\n\n' +
'Er is echter een oplossing: laat burgers zélf de hete aardappels uit het vuur halen. Goed geïnformeerde burgers begrijpen de ernst van de situatie en de noodzaak om verregaande maatregelen te nemen. Omgeven door experten kunnen ze deze maatregelen concretiseren en omzetten in voorstellen tot wetswijzigingen of decreten. Overal ter wereld en vooral in Europa doen andere naties ons dit voor. Onlangs rondde het VK deze oefening af, eerder dit jaar kondigde Frankrijk het resultaat van haar Convention Citoyenne pour le Climat aan. Waarom blijft België - nochtans niet de beste leerling van de klas - achter?\n\n' +
'Enkel organisaties bundelden hun krachten en werkten een concreet voorstel uit om in België ook een gelijkaardig burgerparlement in te voeren, met als doel de klimaatcrisis en de vele andere ecologische uitdagingen aan te pakken. Het is een win-win-win: op die manier investeert België in de toekomst, komt het tegemoet aan de Europese doelstellingen, terwijl geen enkele partij ervoor afgestraft hoeft te worden.\n\n' +
'Ik stelde afgelopen verkiezingen mijn vertrouwen in u en uw partij. Ik hoop dan ook dat u mijn bezorgdheid deelt omtrent de ecologische crisissen, en dat u net als mij, en burgers in vele andere landen, gelooft dat een burgerparlement wellicht nog de enige realistische uitweg is. Neem een kijkje op https://www.hetburgerparlement.be/voorstel. Daar wordt de precariteit van de situatie goed uitgelegd; waarom er tot nu toe onvoldoende aan kon worden gedaan; en waarom een burgerparlement wel een oplossing kan bieden. Lees het voorstel door, bespreek het binnen uw partij en in het parlement. Mijn hoop, en de toekomst van mijzelf en die van duizenden generaties na mij, ligt in uw handen.\n\n' +
'Met bezorgde maar hoopvolle groeten,\n\n'
];

export const FR_SUBJECTS = [
  'FR - Richt een burgerparlement om te ontkomen aan ecologische rampen',
  'FR - Laat burgers zelf maatregelen kiezen tegen ecologische crisissen!',
  'FR - De oplossing voor de ecologische crisissen: een burgerparlement',
  'FR - Laat burgers de hete ecologische aardappels voor u uit het vuur halen',
  'FR - Nu of nooit: de oplossing voor de klimaat- en andere ecologische crisissen',
  'FR - De toekomst van onze generatie, en duizenden na mij, ligt in uw handen',
  'FR - Alternatief voor de partijpolitiek: het burgerparlement',
];

export const FR_BODIES = ['FR- Het wordt steeds duidelijker dat er enkele zeer zware crisissen op ons afkomen. De klimaatverandering is vandaag al een feit. Dat België al 2,5 graden opgewarmd is, hebben we afgelopen twee zomers zelf ondervonden. Door de aanhoudende droogte zitten onze boeren met de handen in het haar. En wij in welvarende landen hebben dan nog het minst te vrezen. Maar klimaatverandering is lang niet de enige onrustwekkende ramp die voor de deur staat. WWF rapporteerde zopas in haar \'Living Planet report\' dat 2/3 van de dierenpopulaties verdwenen is in de afgelopen 50 jaar. En de VN rapporteerden zonet dat geen enkel van de 20 doelen rond biodiversiteit volledig bereikt werd. Om het tij echt te keren zijn drastische maatregelen nodig, stellen ze.\n\n' +
'Ook Europa erkent de problemen en legt haar deelstaten ingrijpende targets op. Europa zal tegen 2030 haar uitstoot met 55% verminderen ten opzichte van 1990. Ook België en Vlaanderen zullen hierin moeten meegaan. Hoe gaan we dat voor mekaar krijgen?\n\n' +
'Het laaghangend fruit is al lang geplukt. En na ellenlange onderhandelingen slaagde België er niet in een ambitieuzer doel dan een 35% reductie voor te leggen aan Europa (en het is nog niet zeker of we dat halen). Ik begrijp dat het onmogelijk wordt om nog hogere reducties waar te maken - zonder stringente maatregelen. En ik begrijp ook dat geen enkele partij deze durft voor te stellen, uit angst voor stemmenverlies. Ziedaar de patstelling.\n\n' +
'Er is echter een oplossing: laat burgers zélf de hete aardappels uit het vuur halen. Goed geïnformeerde burgers begrijpen de ernst van de situatie en de noodzaak om verregaande maatregelen te nemen. Omgeven door experten kunnen ze deze maatregelen concretiseren en omzetten in voorstellen tot wetswijzigingen of decreten. Overal ter wereld en vooral in Europa doen andere naties ons dit voor. Onlangs rondde het VK deze oefening af, eerder dit jaar kondigde Frankrijk het resultaat van haar Convention Citoyenne pour le Climat aan. Waarom blijft België - nochtans niet de beste leerling van de klas - achter?\n\n' +
'Enkel organisaties bundelden hun krachten en werkten een concreet voorstel uit om in België ook een gelijkaardig burgerparlement in te voeren, met als doel de klimaatcrisis en de vele andere ecologische uitdagingen aan te pakken. Het is een win-win-win: op die manier investeert België in de toekomst, komt het tegemoet aan de Europese targets, terwijl geen enkele partij ervoor afgestraft hoeft te worden.\n\n' +
'Ik stelde afgelopen verkiezingen mijn vertrouwen in u en uw partij. Ik hoop dan ook dat u mijn bezorgdheid deelt omtrent de ecologische crisissen, en dat u net als mij, en burgers in vele andere landen, gelooft dat een burgerparlement wellicht nog de enige realistische uitweg is. Neem een kijkje op https://www.hetburgerparlement.be/voorstel. Daar wordt de precariteit van de situatie goed uitgelegd; waarom er tot nu toe onvoldoende aan kon worden gedaan; en waarom een burgerparlement wel een oplossing kan bieden. Lees het voorstel door, bespreek het binnen uw partij en in het parlement. Mijn hoop, en de toekomst van mijzelf en die van duizenden generaties na mij, ligt in uw handen.'
];
