import { MP } from '../mp';

export const mpsBrussels: MP[] = [
  {
      "id": "ADELO",
      "firstName": "Ariane",
      "lastName": " Lobkowicz",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "adelobkowicz@yahoo.fr",
      "party": "DéFI",
      "localImg": "brussels/delobkowicz2019.jpg"
  },
  {
      "id": "AGICL",
      "firstName": "Leila",
      "lastName": " Agic",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "lagic@parlement.brussels",
      "party": "PS",
      "localImg": "brussels/agic2019.jpg"
  },
  {
      "id": "AITBA",
      "firstName": "Latifa",
      "lastName": " Baala",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "latifa.aitbaala@parlement.brussels",
      "party": "MR",
      "localImg": "brussels/baala2019.jpg"
  },
  {
      "id": "AUSTR",
      "firstName": "Victoria",
      "lastName": " Austraet",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "victoria.austraet@parlement.brussels",
      "party": "",
      "localImg": "brussels/austraet2019.jpg"
  },
  {
      "id": "BARZI",
      "firstName": "Clémentine",
      "lastName": " Barzin",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "cbarzin@hotmail.com",
      "party": "MR",
      "localImg": "brussels/barzin2019.jpg"
  },
  {
      "id": "BOMEL",
      "firstName": "Nicole",
      "lastName": " Nketo",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "nbomele@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/bomele2019.jpg"
  },
  {
      "id": "BORRE",
      "firstName": "Mathias",
      "lastName": " Borre",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Dundee (Schotland)",
      "email": "mathias.vandenborre@n-va.be",
      "party": "N-VA",
      "localImg": "brussels/vandenborre.jpg"
  },
  {
      "id": "CASIE",
      "firstName": "Martin",
      "lastName": " Casier",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "martin.casier@parlement.brussels",
      "party": "PS",
      "localImg": "brussels/casier2019.jpg"
  },
  {
      "id": "CHABB",
      "firstName": "Delphine",
      "lastName": " Chabbert",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "delphine.chabbert@parlement.brussels",
      "party": "PS",
      "localImg": "brussels/chabbert2019.jpg"
  },
  {
      "id": "COOMA",
      "firstName": "Geoffroy",
      "lastName": " Brachène",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "contact@coomans.be ",
      "party": "MR",
      "localImg": "brussels/coomans2019.jpg"
  },
  {
      "id": "CZEKA",
      "firstName": "Aurélie",
      "lastName": " Czekalski",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "aurelie.czekalski@parlement.brussels",
      "party": "MR",
      "localImg": "brussels/czekalski2019.jpg"
  },
  {
      "id": "DAGRI",
      "firstName": "Francis",
      "lastName": " Dagrin",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "francis.dagrin@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/dagrin2019.jpg"
  },
  {
      "id": "DEBEU",
      "firstName": "Christophe",
      "lastName": " Beukelaer",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "christophe.debeukelaer@parlement.brussels",
      "party": "cdH",
      "localImg": "brussels/debeukelaer2019.jpg"
  },
  {
      "id": "DEBOC",
      "firstName": "Caroline",
      "lastName": " Bock",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "caroline.debock@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/cdebock2019.jpg"
  },
  {
      "id": "DEPAJ",
      "firstName": "Jonathan",
      "lastName": " Patoul",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "jdepatoul@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/depatoul2019.jpg"
  },
  {
      "id": "DERAB",
      "firstName": "Barbara",
      "lastName": " Radigués",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "barbara.deradigues@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/deradigues2019.jpg"
  },
  {
      "id": "DERE",
      "firstName": "Margaux",
      "lastName": " Ré",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "margaux.dere@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/dere2019.jpg"
  },
  {
      "id": "DONME",
      "firstName": "Ibrahim",
      "lastName": " Dönmez",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "idonmez@parlement.brussels",
      "party": "PS",
      "localImg": "brussels/donmez2019.jpg"
  },
  {
      "id": "DUFOU",
      "firstName": "Dominique",
      "lastName": " Dufourny",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Elsene",
      "email": "dufourny.dominique@gmail.com",
      "party": "MR",
      "localImg": "brussels/dufourny2019.jpg"
  },
  {
      "id": "GOIDS",
      "firstName": "Gaëtan",
      "lastName": " Goidsenhoven",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "email": "gvangoidsenhoven@anderlecht.brussels",
      "party": "MR",
      "localImg": "brussels/vangoidsenhoven.jpg"
  },
  {
      "id": "GROPP",
      "firstName": "Elisa",
      "lastName": " Groppi",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "elisa.groppi@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/groppi2019.jpg"
  },
  {
      "id": "HOESS",
      "firstName": "Soetkin",
      "lastName": " Hoessen",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "soetkin.hoessen@groen.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/hoessen2019.jpg"
  },
  {
      "id": "IKAZB",
      "firstName": "Jamal",
      "lastName": " Ikazban",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Etterbeek",
      "email": "jamal.ikazban@hotmail.com",
      "party": "PS",
      "localImg": "brussels/ikazban2019.jpg"
  },
  {
      "id": "JAMOU",
      "firstName": "Véronique",
      "lastName": " Jamoulle",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Waremme",
      "email": "veronique.jamoulle@skynet.be",
      "party": "PS",
      "localImg": "brussels/jamoulle2019.jpg"
  },
  {
      "id": "KAZAD",
      "firstName": "Gladys",
      "lastName": " Kaniki",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Nijvel",
      "email": "gkazadi@parlement.brussels",
      "party": "cdH",
      "localImg": "brussels/kazadi2019.jpg"
  },
  {
      "id": "KERCK",
      "firstName": "Jean-Pierre",
      "lastName": " Kerckhofs",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "jeanpierre.kerckhofs@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/kerckhofs2019.jpg"
  },
  {
      "id": "KOKSA",
      "firstName": "Sadik",
      "lastName": " Köksal",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "sadik.koksal@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/koksal2019.jpg"
  },
  {
      "id": "KOMPA",
      "firstName": "Pierre",
      "lastName": " Kompany",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Bukavu (D.R. Congo)",
      "email": "pierre@pierrekompany.be",
      "party": "cdH",
      "localImg": "brussels/kompany2019.jpg"
  },
  {
      "id": "KOPLO",
      "firstName": "Stéphanie",
      "lastName": " Koplowicz",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkle",
      "email": "stephanie.koplowicz@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/koplowicz2019.jpg"
  },
  {
      "id": "KOYUN",
      "firstName": "Hasan",
      "lastName": " Koyuncu",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "hasan.koyuncu@hotmail.be",
      "party": "PS",
      "localImg": "brussels/koyuncu2019.jpg"
  },
  {
      "id": "LAANA",
      "firstName": "Fadila",
      "lastName": " Laanan",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Schaarbeek",
      "email": "fadila.laanan@gmail.com",
      "party": "PS",
      "localImg": "brussels/laanan2019.jpg"
  },
  {
      "id": "LECOC",
      "firstName": "Marie",
      "lastName": " Lecocq",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "marie.lecocq@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/lecocq2019.jpg"
  },
  {
      "id": "LEFRA",
      "firstName": "Véronique",
      "lastName": " Lefrancq",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "veronique.lefrancq@parlement.brussels",
      "party": "cdH",
      "localImg": "brussels/lefrancq2019.jpg"
  },
  {
      "id": "LEIST",
      "firstName": "David",
      "lastName": " Leisterh",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "david.leisterh@parlement.brussels",
      "party": "MR",
      "localImg": "brussels/leisterh2019.jpg"
  },
  {
      "id": "LLAHS",
      "firstName": "Leila",
      "lastName": " Lahssaini",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "leila.lahssaini@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/lahssaini2019.jpg"
  },
  {
      "id": "LUX",
      "firstName": "Pierre-Yves",
      "lastName": " Lux",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "pierre-yves.lux@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/lux2019.jpg"
  },
  {
      "id": "MAGDA",
      "firstName": "Christophe",
      "lastName": " Magdalijns",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "cmagdalijns@auderghem.brussels",
      "party": "DéFI",
      "localImg": "brussels/magdalijns2019.jpg"
  },
  {
      "id": "MAISJ",
      "firstName": "Joëlle",
      "lastName": " Maison",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Elsene",
      "email": "jmaison@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/maison2019.jpg"
  },
  {
      "id": "MAMPA",
      "firstName": "Bertin",
      "lastName": " Mankamba",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Kinshasa",
      "email": "bertin.mampaka@mampaka.be",
      "party": "MR",
      "localImg": "brussels/mampaka2014.jpg"
  },
  {
      "id": "MOUHS",
      "firstName": "Ahmed",
      "lastName": " Mouhssin",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "ahmed.mouhssin@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/mouhssin2019.jpg"
  },
  {
      "id": "NAGY",
      "firstName": "Marie",
      "lastName": " Nagy",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "marie.nagy28@gmail.com",
      "party": "DéFI",
      "localImg": "brussels/nagy2019.jpg"
  },
  {
      "id": "OBOLE",
      "firstName": "Petya",
      "lastName": " Obolensky",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "petya.obolensky@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/obolensky2019.jpg"
  },
  {
      "id": "OURIA",
      "firstName": "Mohamed",
      "lastName": " Ouriaghli",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Hasselt",
      "email": "mohamed.ouriaghli@brucity.be",
      "party": "PS",
      "localImg": "brussels/ouriaghli2019.jpg"
  },
  {
      "id": "OZKAR",
      "firstName": "Emin",
      "lastName": " Özkara",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Emirdag (Turkije)",
      "email": "secretariat.ozkara@gmail.com",
      "party": "",
      "localImg": "brussels/ozkara2019.jpg"
  },
  {
      "id": "PARMI",
      "firstName": "Ingrid",
      "lastName": " Parmentier",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "ingrid.parmentier@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/parmentier2019.jpg"
  },
  {
      "id": "PAUTH",
      "firstName": "Isabelle",
      "lastName": " Pauthier",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "isabelle.pauthier@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/pauthier2019.jpg"
  },
  {
      "id": "PLOVI",
      "firstName": "Magali",
      "lastName": " Plovie",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "magali.plovie@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/plovie2019.jpg"
  },
  {
      "id": "ROBER",
      "firstName": "Tristan",
      "lastName": " Roberti",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "tristan.roberti@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/roberti2019.jpg"
  },
  {
      "id": "ROCHE",
      "firstName": "Els",
      "lastName": " Rochette",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Leuven",
      "email": "erochette@parlement.brussels",
      "party": "spa.a",
      "localImg": "brussels/rochette2019.jpg"
  },
  {
      "id": "SCHEP",
      "firstName": "Françoise",
      "lastName": " Schepmans",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "schepmansf@gmail.com",
      "party": "MR",
      "localImg": "brussels/schepmans2019.jpg"
  },
  {
      "id": "SEGER",
      "firstName": "Matteo",
      "lastName": " Segers",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Elsene",
      "email": "matteo.segers@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/segers2019.jpg"
  },
  {
      "id": "SOIRE",
      "firstName": "Kalvin",
      "lastName": " Njall",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "kalvin.soiresse@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/soiresse2019.jpg"
  },
  {
      "id": "TAHAR",
      "firstName": "Farida",
      "lastName": " Tahar",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "farida.tahar@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/tahar2019.jpg"
  },
  {
      "id": "TEITE",
      "firstName": "Viviane",
      "lastName": " Teitelbaum",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Antwerpen ",
      "email": "viviane@teitelbaum.brussels",
      "party": "MR",
      "localImg": "brussels/teitelbaum2019.jpg"
  },
  {
      "id": "TEMIZ",
      "firstName": "Sevket",
      "lastName": " Temiz",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ishakusagi (Turkije)",
      "email": "stemiz@parlbru.irisnet.be",
      "party": "PS",
      "localImg": "brussels/temiz2019.jpg"
  },
  {
      "id": "UYTTE",
      "firstName": "Julien",
      "lastName": " Uyttendaele",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Anderlecht",
      "email": "julien@uyttendaele.brussels",
      "party": "PS",
      "localImg": "brussels/uyttendaele2019.jpg"
  },
  {
      "id": "VANCA",
      "firstName": "Luc",
      "lastName": " Vancauwenberge",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Opbrakel",
      "email": "luc.vancauwenberge@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/vancauwenberge2019.jpg"
  },
  {
      "id": "VOSSA",
      "firstName": "Michaël",
      "lastName": " Vossaert",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "mvossaert@defi.eu",
      "party": "DéFI",
      "localImg": "brussels/vossaert.jpg"
  },
  {
      "id": "WEYTS",
      "firstName": "David",
      "lastName": " Weytsman",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Luik",
      "email": "david.weytsman@brucity.be",
      "party": "MR",
      "localImg": "brussels/davidweytsman.jpg"
  },
  {
      "id": "YOUSF",
      "firstName": "Nadia",
      "lastName": " Yousfi",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Casablanca (Marokko)",
      "email": "nelyousfi@parlbru.irisnet.be",
      "party": "PS",
      "localImg": "brussels/elyousfi2019.jpg"
  },
  {
      "id": "ZAMOU",
      "firstName": "Khadija",
      "lastName": " Zamouri",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Antwerpen",
      "email": "khadija.zamouri@parlement.brussels",
      "party": "Open Vld",
      "localImg": "brussels/zamouri.jpg"
  },
  {
      "id": "BENJU",
      "firstName": "Juan",
      "lastName": " Moreno",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sevilla",
      "email": "juan.benjumea@groen.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/benjumea2019.jpg"
  },
  {
      "id": "DEWOL",
      "firstName": "Vincent",
      "lastName": " Wolf",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel ",
      "email": "vincent.dewolf@etterbeek.be",
      "party": "MR",
      "localImg": "brussels/dewolf2019.jpg"
  },
  {
      "id": "EMMER",
      "firstName": "Isabelle",
      "lastName": " Emmery",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Anderlecht",
      "email": "iemmery@skynet.be",
      "party": "PS",
      "localImg": "brussels/emmery2019.jpg"
  },
  {
      "id": "GENOT",
      "firstName": "Zoé",
      "lastName": " Genot",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "zoe.genot@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/genot2019.jpg"
  },
  {
      "id": "GHYSS",
      "firstName": "Marc-Jean",
      "lastName": " Ghyssels",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sint-Agatha-Berchem",
      "email": "ghyssels.mj@gmail.com",
      "party": "PS",
      "localImg": "brussels/ghyssels2019.jpg"
  },
  {
      "id": "HANDI",
      "firstName": "Youssef",
      "lastName": " Handichi",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "AKLIM (Marokko)",
      "email": "youssef.handichi@gmail.com",
      "party": "PVDA-PTB",
      "localImg": "brussels/handichi2019.jpg"
  },
  {
      "id": "HENGE",
      "firstName": "Guy",
      "lastName": " Vanhengel",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "guy.vanhengel@skynet.be",
      "party": "Open Vld",
      "localImg": "brussels/vanhengel2019v2.jpg"
  },
  {
      "id": "LOEWE",
      "firstName": "Marc",
      "lastName": " Loewenstein",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "email": "marc.loewenstein@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/loewenstein2019.jpg"
  },
  {
      "id": "MADRA",
      "firstName": "Rachid",
      "lastName": " Madrane",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "email": "presidence@parlement.brussels",
      "party": "PS",
      "localImg": "brussels/madrane2019.jpg"
  },
  {
      "id": "SABBE",
      "firstName": "Hilde",
      "lastName": " Sabbe",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Roeselare",
      "email": "hlsabbe@gmail.com",
      "party": "spa.a",
      "localImg": "brussels/sabbe2019.jpg"
  },
  {
      "id": "STOOP",
      "firstName": "Lotte",
      "lastName": " Stoops",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "lotte.stoops@groen.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/stoops2019.jpg"
  },
  {
      "id": "TALHI",
      "firstName": "Hicham",
      "lastName": " Talhi",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Etterbeek",
      "email": "hicham.talhi@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/talhi2019.jpg"
  },
  {
      "id": "URSEL",
      "firstName": "Anne-Charlotte",
      "lastName": " d'Ursel",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Elsene ",
      "email": "annecharlottedursel@gmail.com",
      "party": "MR",
      "localImg": "brussels/dursel2019.jpg"
  },
  {
      "id": "VERSG",
      "firstName": "Gilles",
      "lastName": " Verstraeten",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Kortrijk",
      "email": "gilles.verstraeten@n-va.be",
      "party": "N-VA",
      "localImg": "brussels/verstraeten.jpg"
  },
  {
      "id": "ACHTE",
      "firstName": "Cieltje",
      "lastName": " Achter",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Asse",
      "email": "cieltje.vanachter@n-va.be",
      "party": "N-VA",
      "localImg": "brussels/vanachter2019.jpg"
  },
  {
      "id": "AHIDA",
      "firstName": "Fouad",
      "lastName": " Ahidar",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Mechelen",
      "email": "fouad.ahidar@parlement.brussels",
      "party": "spa.a",
      "localImg": "brussels/ahidar2019.jpg"
  },
  {
      "id": "BAETS",
      "firstName": "Bianca",
      "lastName": " Debaets",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Eeklo",
      "email": "bianca.debaets@parlement.brussels",
      "party": "CD&V",
      "localImg": "brussels/debaets2019.jpg"
  },
  {
      "id": "BERTR",
      "firstName": "Alexia",
      "lastName": " Bertrand",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "alexia_bertrand@hotmail.com",
      "party": "MR",
      "localImg": "brussels/bertrand2019.jpg"
  },
  {
      "id": "BOCK",
      "firstName": "Emmanuel",
      "lastName": " Bock",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Elsene",
      "email": "emmanuel.debock@parlement.brussels",
      "party": "DéFI",
      "localImg": "brussels/edebock2019.jpg"
  },
  {
      "id": "BUSSE",
      "firstName": "Jan",
      "lastName": " Busselen",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Hasselt",
      "email": "jan.busselen@pvda.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/busselen2019.jpg"
  },
  {
      "id": "CHAHR",
      "firstName": "Ridouane",
      "lastName": " Chahid",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "email": "ridouanechahid@gmail.com",
      "party": "PS",
      "localImg": "brussels/chahid2019.jpg"
  },
  {
      "id": "DEJON",
      "firstName": "Carla",
      "lastName": " Dejonghe",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Etterbeek ",
      "email": "carla.dejonghe@parlement.brussels",
      "party": "Open Vld",
      "localImg": "brussels/dejonghe2014.jpg"
  },
  {
      "id": "DESME",
      "firstName": "Françoise",
      "lastName": " Smedt",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "francoise.desmedt@ptb.be",
      "party": "PVDA-PTB",
      "localImg": "brussels/desmedt2019.jpg"
  },
  {
      "id": "FREMA",
      "firstName": "Céline",
      "lastName": " Fremault",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkle",
      "email": "fremault.c@gmail.com",
      "party": "cdH",
      "localImg": "brussels/fremault2019.jpg"
  },
  {
      "id": "KENNI",
      "firstName": "Pepijn",
      "lastName": " Kennis",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Leuven",
      "email": "pepijn.kennis@parlement.brussels",
      "party": "Agora",
      "localImg": "brussels/kennis2019.jpg"
  },
  {
      "id": "LOOTE",
      "firstName": "Dominiek",
      "lastName": " Lootens-Stael",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Torhout",
      "email": "dominiek.lootens-stael@parlement.brussels",
      "party": "VB",
      "localImg": "brussels/lootens2019.jpg"
  },
  {
      "id": "PITSE",
      "firstName": "John",
      "lastName": " Pitseys",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "email": "john.pitseys@ecolo.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/pitseys2019.jpg"
  },
  {
      "id": "VERST",
      "firstName": "Arnaud",
      "lastName": " Verstraete",
      "parliament": "Brussels Parliament",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Deinze",
      "email": "arnaud.verstraete@groen.be",
      "party": "Ecolo-Groen",
      "localImg": "brussels/verstraete2019.jpg"
  }
];
