import { MP } from '../mp';

export const members: MP[] = [
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07508",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "federal/07508.jpg",
      "firstName": "Björn",
      "lastName": "Anseeuw"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "07124",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Anderlecht",
      "language": "Frans",
      "localImg": "federal/07124.jpg",
      "firstName": "Khalil",
      "lastName": "Aouasti"
  },
  {
      "parliament": "Federal",
      "party": "cdH",
      "email": "josy.arens@lachambre.be",
      "id": "00866",
      "constituency": "Luxemburg",
      "hometown": "Aarlen",
      "language": "Frans",
      "localImg": "federal/00866.jpg",
      "firstName": "Josy",
      "lastName": "Arens"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "07169",
      "constituency": "Henegouwen",
      "hometown": "Dinant",
      "language": "Frans",
      "localImg": "federal/07169.jpg",
      "firstName": "Hugues",
      "lastName": "Bayet"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "06733",
      "constituency": "Luik",
      "hometown": "Verviers",
      "language": "Frans",
      "localImg": "federal/06733.jpg",
      "firstName": "Malik",
      "lastName": "Ben Achour"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "06172",
      "constituency": "Antwerpen",
      "hometown": "Herentals",
      "language": "Nederlands",
      "localImg": "federal/06172.jpg",
      "firstName": "Jan",
      "lastName": "Bertels"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "07254",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/07254.jpg",
      "firstName": "Mathieu",
      "lastName": "Bihet"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "hendrik.bogaert@dekamer.be",
      "id": "01039",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "federal/01039.gif",
      "firstName": "Hendrik",
      "lastName": "Bogaert"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "06934",
      "constituency": "Namen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "federal/06934.jpg",
      "firstName": "Christophe",
      "lastName": "Bombled"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07133",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Dujda (Marokko)",
      "language": "Frans",
      "localImg": "federal/07133.jpg",
      "firstName": "Nabil",
      "lastName": "Boukili"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "07346",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/07346.jpg",
      "firstName": "Jan",
      "lastName": "Briers"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "emmanuel.burton@lachambre.be",
      "id": "O1057",
      "constituency": "Waals-Brabant",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "federal/O1057.gif",
      "firstName": "Emmanuel",
      "lastName": "Burton"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "katleen.bury@dekamer.be",
      "id": "07425",
      "constituency": "Vlaams-Brabant",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "federal/07425.jpg",
      "firstName": "Katleen",
      "lastName": "Bury"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "06030",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Sint-Niklaas",
      "language": "Nederlands",
      "localImg": "federal/06030.gif",
      "firstName": "Peter",
      "lastName": "Buysrogge"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07010",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "federal/07010.jpg",
      "firstName": "Kim",
      "lastName": "Buyst"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "kristof.calvo@dekamer.be",
      "id": "06128",
      "constituency": "Antwerpen",
      "hometown": "Rumst",
      "language": "Nederlands",
      "localImg": "federal/06128.gif",
      "firstName": "Kristof",
      "lastName": "Calvo"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07245",
      "constituency": "Luik",
      "hometown": "Verviers",
      "language": "Frans",
      "localImg": "federal/07245.jpg",
      "firstName": "Julie",
      "lastName": "Chanson"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "samuel.cogolati@huy.be",
      "id": "07244",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/07244.jpg",
      "firstName": "Samuel",
      "lastName": "Cogolati"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07271",
      "constituency": "Luik",
      "hometown": "Genk",
      "language": "Frans",
      "localImg": "federal/07271.jpg",
      "firstName": "Gaby",
      "lastName": "Colebunders"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07199",
      "constituency": "Limburg",
      "hometown": "Maaseik",
      "language": "Nederlands",
      "localImg": "federal/07199.jpg",
      "firstName": "Barbara",
      "lastName": "Creemers"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "steven.creyelman@vlaamsbelang.org",
      "id": "06873",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "federal/06873.jpg",
      "firstName": "Steven",
      "lastName": "Creyelman"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "email": "john.crombez@s-p-a.be",
      "id": "01307",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "localImg": "federal/01307.jpg",
      "firstName": "John",
      "lastName": "Crombez",
      "language": "Nederlands"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07048",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "federal/07048.jpg",
      "firstName": "Greet",
      "lastName": "Daems"
  },
  {
      "parliament": "Federal",
      "party": "cdH",
      "email": "georges.dallemagne@lachambre.be",
      "id": "00951",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Fataki (DRC)",
      "language": "Frans",
      "localImg": "federal/00951.jpg",
      "firstName": "Georges",
      "lastName": "Dallemagne"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07182",
      "constituency": "Henegouwen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "federal/07182.jpg",
      "firstName": "Roberto",
      "lastName": "D'Amico"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "info@robbydecaluwe.be",
      "id": "07358",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Lokeren",
      "language": "Nederlands",
      "localImg": "federal/07358.jpg",
      "firstName": "Robby",
      "lastName": "De Caluwé"
  },
  {
      "parliament": "Federal",
      "party": "ONAFH",
      "email": "jean-marie.dedecker@dekamer.be",
      "id": "00954",
      "constituency": "West-Vlaanderen",
      "hometown": "Nieuwpoort",
      "language": "Nederlands",
      "localImg": "federal/00954.jpg",
      "firstName": "Jean-Marie",
      "lastName": "Dedecker"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "ludivine.dedonder@tournai.be",
      "id": "06336",
      "constituency": "Henegouwen",
      "hometown": "Doornik",
      "language": "Frans",
      "localImg": "federal/06336.jpg",
      "firstName": "Ludivine",
      "lastName": "Dedonder"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "burgemeester@ninove.be",
      "id": "07352",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Ninove",
      "language": "Nederlands",
      "localImg": "federal/07352.jpg",
      "firstName": "Tania",
      "lastName": "De Jonge"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07111",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "federal/07111.jpg",
      "firstName": "Séverine",
      "lastName": "de Laveleye"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "jean-marc.delizee@lachambre.be",
      "id": "00746",
      "constituency": "Namen",
      "hometown": "Oignies-en-Thiérache",
      "language": "Frans",
      "localImg": "federal/00746.gif",
      "firstName": "Jean-Marc",
      "lastName": "Delizée"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "id": "07419",
      "constituency": "Vlaams-Brabant",
      "hometown": "Tienen",
      "language": "Nederlands",
      "localImg": "federal/07419.jpg",
      "firstName": "Bram",
      "lastName": "Delvaux"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "07122",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "federal/07122.jpg",
      "firstName": "Michel",
      "lastName": "De Maegd"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "franky.demon@dekamer.be",
      "id": "06805",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "federal/06805.gif",
      "firstName": "Franky",
      "lastName": "Demon"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07387",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "federal/07387.jpg",
      "firstName": "Kathleen",
      "lastName": "Depoorter"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "ortwin.depoortere@vlaamsbelang.org",
      "id": "01129",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Izegem",
      "language": "Nederlands",
      "localImg": "federal/01129.jpg",
      "firstName": "Ortwin",
      "lastName": "Depoortere"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "07494",
      "constituency": "West-Vlaanderen",
      "hometown": "Kortrijk",
      "language": "Nederlands",
      "localImg": "federal/07494.jpg",
      "firstName": "Melissa",
      "lastName": "Depraetere"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "peter.deroover@dekamer.be",
      "id": "06588",
      "constituency": "Antwerpen",
      "hometown": "Turnhout",
      "language": "Nederlands",
      "localImg": "federal/06588.gif",
      "firstName": "Peter",
      "lastName": "De Roover"
  },
  {
      "parliament": "Federal",
      "party": "DéFI",
      "email": "fdesmet@defi.eu",
      "id": "07100",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "federal/07100.jpg",
      "firstName": "François",
      "lastName": "De Smet"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "pieter.despiegeleer@dekamer.be",
      "id": "07339",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Zottegem",
      "language": "Nederlands",
      "localImg": "federal/07339.jpg",
      "firstName": "Pieter",
      "lastName": "De Spiegeleer"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "wouter.de.vriendt@dekamer.be",
      "id": "01199",
      "constituency": "West-Vlaanderen",
      "hometown": "Oostende",
      "language": "Nederlands",
      "localImg": "federal/01199.gif",
      "firstName": "Wouter",
      "lastName": "De Vriendt"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07399",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/07399.jpg",
      "firstName": "Steven",
      "lastName": "De Vuyst"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "patrick.dewael@dekamer.be",
      "id": "00124",
      "constituency": "Limburg",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "federal/00124.gif",
      "firstName": "Patrick",
      "lastName": "Dewael"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "sophie.dewit@dekamer.be",
      "id": "06141",
      "constituency": "Antwerpen",
      "hometown": "Deurne",
      "language": "Nederlands",
      "localImg": "federal/06141.gif",
      "firstName": "Sophie",
      "lastName": "De Wit"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "nathalie.dewulf@vlaamsbelang.org",
      "id": "07477",
      "constituency": "West-Vlaanderen",
      "hometown": "Izegem",
      "language": "Nederlands",
      "localImg": "federal/07477.jpg",
      "firstName": "Nathalie",
      "lastName": "Dewulf"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "christoph.dhaese@dekamer.be",
      "id": "06907",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Aalst",
      "language": "Nederlands",
      "localImg": "federal/06907.gif",
      "firstName": "Christoph",
      "lastName": "D'Haese"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "leen.dierick@dekamer.be",
      "id": "01201",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "federal/01201.gif",
      "firstName": "Leen",
      "lastName": "Dierick"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "marijke.dillen@outlook.be",
      "id": "00636",
      "constituency": "Antwerpen",
      "hometown": "Mortsel",
      "language": "Nederlands",
      "localImg": "federal/00636.jpg",
      "firstName": "Marijke",
      "lastName": "Dillen"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "07255",
      "constituency": "Luik",
      "hometown": "Hoei",
      "language": "Frans",
      "localImg": "federal/anonymous.jpg",
      "firstName": "Magali",
      "lastName": "Dock"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07207",
      "constituency": "Limburg",
      "hometown": "Hasselt",
      "language": "Nederlands",
      "localImg": "federal/07207.jpg",
      "firstName": "Joy",
      "lastName": "Donné"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "07192",
      "constituency": "Limburg",
      "hometown": "Sarcelles (Frankrijk)",
      "language": "Nederlands",
      "localImg": "federal/07192.jpg",
      "firstName": "Nawal",
      "lastName": "Farih"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "andre.flahaut@lachambre.be",
      "id": "00761",
      "constituency": "Waals-Brabant",
      "hometown": "Walhain",
      "language": "Frans",
      "localImg": "federal/00761.gif",
      "firstName": "André",
      "lastName": "Flahaut"
  },
  {
      "parliament": "Federal",
      "party": "cdH",
      "email": "catherine.fonck@lachambre.be",
      "id": "01076",
      "constituency": "Henegouwen",
      "hometown": "Ciney",
      "language": "Frans",
      "localImg": "federal/01076.gif",
      "firstName": "Catherine",
      "lastName": "Fonck"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "theo.francken@dekamer.be",
      "id": "04666",
      "constituency": "Vlaams-Brabant",
      "hometown": "Lubbeek",
      "language": "Nederlands",
      "localImg": "federal/04666.gif",
      "firstName": "Theo",
      "lastName": "Francken"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "michael.freilich@n-va.be",
      "id": "07022",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "federal/07022.jpg",
      "firstName": "Michael",
      "lastName": "Freilich"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "benoit.friart@lachambre.be",
      "id": "06663",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "federal/06663.gif",
      "firstName": "Benoît",
      "lastName": "Friart"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "katja.gabriels@dekamer.be",
      "id": "06885",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "federal/06885.jpg",
      "firstName": "Katja",
      "lastName": "Gabriëls"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "isabelle.galant@lachambre.be",
      "id": "06665",
      "constituency": "Henegouwen",
      "hometown": "Aat",
      "language": "Frans",
      "localImg": "federal/06665.jpg",
      "firstName": "Isabelle",
      "lastName": "Galant"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "06499",
      "constituency": "Limburg",
      "hometown": "Bree",
      "language": "Nederlands",
      "localImg": "federal/06499.jpg",
      "firstName": "Frieda",
      "lastName": "Gijbels"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "erik.gilissen@dekamer.be",
      "id": "07228",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "federal/07228.jpg",
      "firstName": "Erik",
      "lastName": "Gilissen"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "georges.gilkinet@lachambre.be",
      "id": "01205",
      "constituency": "Namen",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "federal/01205.gif",
      "firstName": "Georges",
      "lastName": "Gilkinet"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "O599",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "federal/O599.jpg",
      "firstName": "Nathalie",
      "lastName": "Gilson"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "deputegoblet@outlook.com",
      "id": "07261",
      "constituency": "Luik",
      "hometown": "Herve",
      "language": "Frans",
      "localImg": "federal/07261.jpg",
      "firstName": "Marc",
      "lastName": "Goblet"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "07295",
      "constituency": "Luxemburg",
      "hometown": "Aarlen",
      "language": "Frans",
      "localImg": "federal/07295.jpg",
      "firstName": "Mélissa",
      "lastName": "Hanus"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "email": "raoul.hedebouw@lachambre.be",
      "id": "06759",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/06759.gif",
      "firstName": "Raoul",
      "lastName": "Hedebouw"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "06309",
      "constituency": "Henegouwen",
      "hometown": "Gosselies",
      "language": "Frans",
      "localImg": "federal/06309.jpg",
      "firstName": "Laurence",
      "lastName": "Hennuy"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07417",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "federal/07417.jpg",
      "firstName": "Katrien",
      "lastName": "Houtmeyers"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07481",
      "constituency": "West-Vlaanderen",
      "hometown": "Duinkerke-Noord (Frankrijk)",
      "language": "Nederlands",
      "localImg": "federal/07481.jpg",
      "firstName": "Yngvild",
      "lastName": "Ingels"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "01207",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/01207.gif",
      "firstName": "Kattrin",
      "lastName": "Jadin"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "01070",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "federal/01070.gif",
      "firstName": "Karin",
      "lastName": "Jiroflée"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "zakia.khattabi@ecolo.be",
      "id": "01310",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sint-Joost-ten-Node",
      "language": "Frans",
      "localImg": "federal/01310.gif",
      "firstName": "Zakia",
      "lastName": "Khattabi"
  },
  {
      "parliament": "Federal",
      "party": "ONAFH",
      "email": "emir.kir@lachambre.be",
      "id": "06645",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "federal/06645.gif",
      "firstName": "Emir",
      "lastName": "Kir"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "email": "meryame@kitir.be ",
      "id": "01209",
      "constituency": "Limburg",
      "hometown": "Maasmechelen",
      "language": "Nederlands",
      "localImg": "federal/01209.gif",
      "firstName": "Meryame",
      "lastName": "Kitir"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "ahmed.laaouej@lachambre.be",
      "id": "06461",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/06461.gif",
      "firstName": "Ahmed",
      "lastName": "Laaouej"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "egbert.lachaert@dekamer.be",
      "id": "06884",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/06884.gif",
      "firstName": "Egbert",
      "lastName": "Lachaert"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "christophe.lacroix@lachambre.be",
      "id": "06389",
      "constituency": "Luik",
      "hometown": "Hoei",
      "language": "Frans",
      "localImg": "federal/06389.jpg",
      "firstName": "Christophe",
      "lastName": "Lacroix"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "01042",
      "constituency": "Antwerpen",
      "hometown": "Borgerhout",
      "language": "Nederlands",
      "localImg": "federal/01042.gif",
      "firstName": "Nahima",
      "lastName": "Lanjri"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "marie-colline.leroy@ecolo.be",
      "id": "07153",
      "constituency": "Henegouwen",
      "hometown": "Baudour",
      "language": "Frans",
      "localImg": "federal/07153.jpg",
      "firstName": "Marie-Colline",
      "lastName": "Leroy"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "id": "07034",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "federal/07034.gif",
      "firstName": "Christian",
      "lastName": "Leysen"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "id": "07448",
      "constituency": "Vlaams-Brabant",
      "hometown": "Aarschot",
      "language": "Nederlands",
      "localImg": "federal/07448.jpg",
      "firstName": "Goedele",
      "lastName": "Liekens"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "06985",
      "constituency": "West-Vlaanderen",
      "hometown": "Veurne",
      "language": "Nederlands",
      "localImg": "federal/06985.jpg",
      "firstName": "Sander",
      "lastName": "Loones"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "07407",
      "constituency": "Vlaams-Brabant",
      "hometown": "Elsene",
      "language": "Nederlands",
      "localImg": "federal/07407.jpg",
      "firstName": "Sammy",
      "lastName": "Mahdi"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "07193",
      "constituency": "Limburg",
      "hometown": "Bree",
      "language": "Nederlands",
      "localImg": "federal/07193.jpg",
      "firstName": "Steven",
      "lastName": "Matheï"
  },
  {
      "parliament": "Federal",
      "party": "cdH",
      "email": "vanessa.matz@lachambre.be",
      "id": "01281",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/01281.gif",
      "firstName": "Vanessa",
      "lastName": "Matz"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "email": "sofie.merckx@ptb.be",
      "id": "07181",
      "constituency": "Henegouwen",
      "hometown": "Wilrijk",
      "language": "Frans",
      "localImg": "federal/07181.jpg",
      "firstName": "Sofie",
      "lastName": "Merckx"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07047",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "federal/07047.jpg",
      "firstName": "Peter",
      "lastName": "Mertens"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "koen.metsu@dekamer.be",
      "id": "06591",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "localImg": "federal/06591.gif",
      "firstName": "Koen",
      "lastName": "Metsu",
      "hometown": "Edegem"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "email": "nadia.moscufo@ptb.be",
      "id": "07270",
      "constituency": "Luik",
      "hometown": "Hermalle-sous-Argenteau",
      "language": "Frans",
      "localImg": "federal/07270.jpg",
      "firstName": "Nadia",
      "lastName": "Moscufo"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "06534",
      "constituency": "Waals-Brabant",
      "hometown": "Ottignies-Louvain-la-Neuve",
      "language": "Frans",
      "localImg": "federal/06534.jpg",
      "firstName": "Simon",
      "lastName": "Moutquin"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "ozlem.ozen@lachambre.be",
      "id": "06326",
      "constituency": "Henegouwen",
      "hometown": "Charleroi",
      "language": "Frans",
      "localImg": "federal/06326.gif",
      "firstName": "Özlem",
      "lastName": "Özen"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "barbara.pas@vlaamsbelang.org",
      "id": "01236",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Temse",
      "language": "Nederlands",
      "localImg": "federal/01236.gif",
      "firstName": "Barbara",
      "lastName": "Pas"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "benoit.piedboeuf@lachambre.be",
      "id": "06423",
      "constituency": "Luxemburg",
      "hometown": "Musienene (DRC)",
      "language": "Frans",
      "localImg": "federal/06423.gif",
      "firstName": "Benoît",
      "lastName": "Piedboeuf"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "philippe@pivin.be",
      "id": "06618",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Sint-Agatha-Berchem",
      "language": "Frans",
      "localImg": "federal/06618.gif",
      "firstName": "Philippe",
      "lastName": "Pivin"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "annick.ponthier@dekamer.be",
      "id": "01292",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "federal/01292.jpg",
      "firstName": "Annick",
      "lastName": "Ponthier"
  },
  {
      "parliament": "Federal",
      "party": "cdH",
      "email": "maxime.prevot@lachambre.be",
      "id": "01216",
      "constituency": "Namen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "federal/01216.jpg",
      "firstName": "Maxime",
      "lastName": "Prévot"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "06967",
      "constituency": "Henegouwen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "federal/06967.jpg",
      "firstName": "Patrick",
      "lastName": "Prévot"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "06498",
      "constituency": "Limburg",
      "hometown": "Bilzen",
      "language": "Nederlands",
      "localImg": "federal/06498.jpg",
      "firstName": "Wouter",
      "lastName": "Raskin"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "kurt.ravyts@vlaamsbelang.org",
      "id": "07485",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "federal/07485.jpg",
      "firstName": "Kurt",
      "lastName": "Ravyts"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "florence.reuter@waterloo.be",
      "id": "01217",
      "constituency": "Waals-Brabant",
      "hometown": "Malmédy",
      "language": "Frans",
      "localImg": "federal/01217.jpg",
      "firstName": "Florence",
      "lastName": "Reuter"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "07263",
      "constituency": "Luik",
      "language": "Frans",
      "localImg": "federal/07263.jpg",
      "firstName": "Hervé",
      "lastName": "Rigot",
      "hometown": "Waremme"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07369",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "federal/07369.jpg",
      "firstName": "Tomas",
      "lastName": "Roggeman"
  },
  {
      "parliament": "Federal",
      "party": "DéFI",
      "email": "srohonyi@defi.eu",
      "id": "07102",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Eigenbrakel",
      "language": "Frans",
      "localImg": "federal/07102.jpg",
      "firstName": "Sophie",
      "lastName": "Rohonyi"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07416",
      "constituency": "Vlaams-Brabant",
      "hometown": "Teheran (Iran)",
      "language": "Nederlands",
      "localImg": "federal/07416.jpg",
      "firstName": "Darya",
      "lastName": "Safai"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "ellen.samyn@dekamer.be",
      "id": "07076",
      "constituency": "Antwerpen",
      "hometown": "Roeselare",
      "language": "Nederlands",
      "localImg": "federal/07076.jpg",
      "firstName": "Ellen",
      "lastName": "Samyn"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "sarah.schlitz@ecolo.be",
      "id": "06722",
      "constituency": "Luik",
      "hometown": "Luik",
      "language": "Frans",
      "localImg": "federal/06722.gif",
      "firstName": "Sarah",
      "lastName": "Schlitz"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "id": "06287",
      "constituency": "Waals Brabant",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "federal/anonymous.jpg",
      "firstName": "Vincent",
      "lastName": "Scourneau"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "07063",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "federal/07063.gif",
      "firstName": "Ben",
      "lastName": "Segers"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "daniel.senesael@lachambre.be",
      "id": "06682",
      "constituency": "Henegouwen",
      "hometown": "Doornik",
      "language": "Frans",
      "localImg": "federal/06682.gif",
      "firstName": "Daniel",
      "lastName": "Senesael"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "bercy.slegers@dekamer.be",
      "id": "04872",
      "constituency": "West-Vlaanderen",
      "hometown": "Poperinge",
      "language": "Nederlands",
      "localImg": "federal/04872.jpg",
      "firstName": "Bercy",
      "lastName": "Slegers"
  },
  {
      "parliament": "Federal",
      "party": "VB ",
      "email": "dominiek.sneppe@dekamer.be",
      "id": "O1330",
      "constituency": "West-Vlaanderen",
      "hometown": "Brugge",
      "language": "Nederlands",
      "localImg": "federal/O1330.jpg",
      "firstName": "Dominiek",
      "lastName": "Sneppe"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07410",
      "constituency": "Vlaams-Brabant",
      "hometown": "Jette",
      "language": "Nederlands",
      "localImg": "federal/07410.jpg",
      "firstName": "Jessika",
      "lastName": "Soors"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "jan.spooren@n-va.be",
      "id": "06841",
      "constituency": "Vlaams-Brabant",
      "hometown": "Herk-de-Stad",
      "localImg": "federal/06841.gif",
      "firstName": "Jan",
      "lastName": "Spooren",
      "language": "Nederlands"
  },
  {
      "parliament": "Federal",
      "party": "MR",
      "email": "caroline.taquin@lachambre.be",
      "id": "07162",
      "constituency": "Henegouwen",
      "hometown": "Nijvel",
      "language": "Frans",
      "localImg": "federal/07162.jpg",
      "firstName": "Caroline",
      "lastName": "Taquin"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "deputee@sophiethemont.be",
      "id": "07262",
      "constituency": "Luik",
      "hometown": "Aat",
      "language": "Frans",
      "localImg": "federal/07262.jpg",
      "firstName": "Sophie",
      "lastName": "Thémont"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "cecile.thibaut@ecolo.be",
      "id": "01309",
      "constituency": "Luxemburg",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "federal/01309.jpg",
      "firstName": "Cécile",
      "lastName": "Thibaut"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "eric.thiebaut@lachambre.be",
      "id": "01222",
      "constituency": "Henegouwen",
      "hometown": "Bergen",
      "language": "Frans",
      "localImg": "federal/01222.gif",
      "firstName": "Eric",
      "lastName": "Thiébaut"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "O2619",
      "constituency": "Namen",
      "hometown": "Namen",
      "language": "Frans",
      "localImg": "federal/O2619.jpg",
      "firstName": "Eliane",
      "lastName": "Tillieux"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "id": "07171",
      "constituency": "Henegouwen",
      "hometown": "Lobbes",
      "language": "Frans",
      "localImg": "federal/07171.jpg",
      "firstName": "Philippe",
      "lastName": "Tison"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "frank.troosters@dekamer.be",
      "id": "07227",
      "constituency": "Limburg",
      "hometown": "Hasselt",
      "language": "Nederlands",
      "localImg": "federal/07227.jpg",
      "firstName": "Frank",
      "lastName": "Troosters"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "07411",
      "constituency": "Vlaams-Brabant",
      "hometown": "Bonheiden",
      "language": "Nederlands",
      "localImg": "federal/07411.jpg",
      "firstName": "Dieter",
      "lastName": "Vanbesien"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "07354",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/07354.jpg",
      "firstName": "Anneleen",
      "lastName": "Van Bossuyt"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "yoleen.vancamp@dekamer.be",
      "id": "06590",
      "constituency": "Antwerpen",
      "hometown": "Wilrijk",
      "language": "Nederlands",
      "localImg": "federal/06590.gif",
      "firstName": "Yoleen",
      "lastName": "Van Camp"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "id": "01131",
      "constituency": "Antwerpen",
      "hometown": "Essen",
      "language": "Nederlands",
      "localImg": "federal/01131.gif",
      "firstName": "Jef",
      "lastName": "Van den Bergh"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "07366",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "federal/07366.jpg",
      "firstName": "Joris",
      "lastName": "Vandenbroucke"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "gilles.vandenburre@lachambre.be",
      "id": "06638",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Brussel",
      "language": "Frans",
      "localImg": "federal/06638.jpg",
      "firstName": "Gilles",
      "lastName": "Vanden Burre"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "tim.vandenput@dekamer.be",
      "id": "06823",
      "constituency": "Vlaams-Brabant",
      "hometown": "Ukkel",
      "language": "Nederlands",
      "localImg": "federal/06823.gif",
      "firstName": "Tim",
      "lastName": "Vandenput"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "id": "06595",
      "constituency": "Antwerpen",
      "hometown": "Oudenaarde",
      "language": "Nederlands",
      "localImg": "federal/06595.gif",
      "firstName": "Wim",
      "lastName": "Van der Donckt"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "id": "01226",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Zoersel",
      "language": "Nederlands",
      "localImg": "federal/01226.jpg",
      "firstName": "Tinne",
      "lastName": "Van der Straeten"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "tom.vangrieken@vlaamsbelang.org",
      "id": "07075",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "federal/07075.jpg",
      "firstName": "Tom",
      "lastName": "Van Grieken"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "stefaan.vanhecke@dekamer.be",
      "id": "01227",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/01227.gif",
      "firstName": "Stefaan",
      "lastName": "Van Hecke"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "email": "marco.vanhees@lachambre.be",
      "id": "06701",
      "constituency": "Henegouwen",
      "hometown": "Sint-Agatha-Berchem",
      "language": "Frans",
      "localImg": "federal/06701.gif",
      "firstName": "Marco",
      "lastName": "Van Hees"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "els.vanhoof@dekamer.be",
      "id": "06852",
      "constituency": "Vlaams-Brabant",
      "hometown": "Leuven",
      "language": "Nederlands",
      "localImg": "federal/anonymous.jpg",
      "firstName": "Els",
      "lastName": "Van Hoof"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "dries.vanlangenhove@dekamer.be",
      "id": "07424",
      "constituency": "Vlaams-Brabant",
      "hometown": "Dendermonde",
      "language": "Nederlands",
      "localImg": "federal/07424.jpg",
      "firstName": "Dries",
      "lastName": "Van Langenhove"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "reccino.vanlommel@vlaamsbelang.org",
      "id": "07077",
      "constituency": "Antwerpen",
      "hometown": "Turnhout",
      "language": "Nederlands",
      "localImg": "federal/07077.jpg",
      "firstName": "Reccino",
      "lastName": "Van Lommel"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "valerie.vanpeel@dekamer.be",
      "id": "06589",
      "constituency": "Antwerpen",
      "hometown": "Ekeren",
      "language": "Nederlands",
      "localImg": "federal/06589.gif",
      "firstName": "Valerie",
      "lastName": "Van Peel"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "vincentvq@mac.com",
      "id": "00972",
      "constituency": "West-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/00972.gif",
      "firstName": "Vincent",
      "lastName": "Van Quickenborne"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "06897",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Lüdenscheid (Duitsland)",
      "language": "Nederlands",
      "localImg": "federal/06897.jpg",
      "firstName": "Anja",
      "lastName": "Vanrobaeys"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "kristien.vanvaerenbergh@dekamer.be",
      "id": "06230",
      "constituency": "Vlaams-Brabant",
      "hometown": "Halle",
      "language": "Nederlands",
      "localImg": "federal/06230.gif",
      "firstName": "Kristien",
      "lastName": "Van Vaerenbergh"
  },
  {
      "parliament": "Federal",
      "party": "sp.a",
      "id": "07219",
      "constituency": "Limburg",
      "hometown": "Lommel",
      "language": "Nederlands",
      "localImg": "federal/07219.jpg",
      "firstName": "Kris",
      "lastName": "Verduyckt"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "id": "07035",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "federal/07035.jpg",
      "firstName": "Marianne",
      "lastName": "Verhaert"
  },
  {
      "parliament": "Federal",
      "party": "Open Vld",
      "email": "kathleen-verhelst@kathleen-verhelst.be",
      "id": "07502",
      "constituency": "West-Vlaanderen",
      "hometown": "Roeselare",
      "language": "Nederlands",
      "localImg": "federal/07502.jpg",
      "firstName": "Kathleen",
      "lastName": "Verhelst"
  },
  {
      "parliament": "Federal",
      "party": "CD&V",
      "email": "servais.verherstraeten@dekamer.be",
      "id": "00826",
      "constituency": "Antwerpen",
      "hometown": "Balen",
      "language": "Nederlands",
      "localImg": "federal/00826.gif",
      "firstName": "Servais",
      "lastName": "Verherstraeten"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "wouter.vermeersch@vlaamsbelang.org",
      "id": "07487",
      "constituency": "West-Vlaanderen",
      "hometown": "Kortrijk",
      "language": "Nederlands",
      "localImg": "federal/07487.jpg",
      "firstName": "Wouter",
      "lastName": "Vermeersch"
  },
  {
      "parliament": "Federal",
      "party": "VB",
      "email": "hans.verreyt@vlaamsbelang.org",
      "id": "07078",
      "constituency": "Antwerpen",
      "hometown": "Antwerpen",
      "language": "Nederlands",
      "localImg": "federal/07078.jpg",
      "firstName": "Hans",
      "lastName": "Verreyt"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "albert.vicaire@ecolo.be",
      "id": "07154",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "federal/07154.jpg",
      "firstName": "Albert",
      "lastName": "Vicaire"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "id": "07137",
      "constituency": "Brussel-Hoofdstad",
      "hometown": "Waregem",
      "language": "Nederlands",
      "localImg": "federal/07137.jpg",
      "firstName": "Maria",
      "lastName": "Vindevoghel"
  },
  {
      "parliament": "Federal",
      "party": "PVDA-PTB",
      "email": "thierry.warmoes@ptb.be",
      "id": "07322",
      "constituency": "Namen",
      "hometown": "Ukkel",
      "language": "Frans",
      "localImg": "federal/07322.jpg",
      "firstName": "Thierry",
      "lastName": "Warmoes"
  },
  {
      "parliament": "Federal",
      "party": "Ecolo-Groen",
      "email": "evita.willaert@groen.be",
      "id": "06861",
      "constituency": "Oost-Vlaanderen",
      "hometown": "Gent",
      "language": "Nederlands",
      "localImg": "federal/06861.gif",
      "firstName": "Evita",
      "lastName": "Willaert"
  },
  {
      "parliament": "Federal",
      "party": "N-VA",
      "email": "bert.wollants@dekamer.be",
      "id": "06147",
      "constituency": "Antwerpen",
      "hometown": "Lier",
      "language": "Nederlands",
      "localImg": "federal/06147.gif",
      "firstName": "Bert",
      "lastName": "Wollants"
  },
  {
      "parliament": "Federal",
      "party": "PS",
      "email": "laurencezanchetta@hotmail.com",
      "id": "07170",
      "constituency": "Henegouwen",
      "hometown": "Haine-Saint-Paul",
      "language": "Frans",
      "localImg": "federal/07170.jpg",
      "firstName": "Laurence",
      "lastName": "Zanchetta"
  }
];
