import { MP } from '../mp/mp';

export const members: MP[] = [
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Meyrem",
      "lastName": "Almaci",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4381",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "meyrem.almaci@groen.be",
      "localImg": "flemish/4381.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Els",
      "lastName": "Ampe",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4382",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "els.ampe@vlaamsparlement.be",
      "localImg": "flemish/4382.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Hannes",
      "lastName": "Anaf",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4383",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "hannes.anaf@vlaamsparlement.be",
      "localImg": "flemish/4383.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Imade",
      "lastName": "Annouri",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4052",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "imade.annouri@vlaamsparlement.be",
      "localImg": "flemish/4052.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Roosmarijn",
      "lastName": "Beckers",
      "city": "Sint-truiden",
      "party": "VB",
      "id": "4384",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "roosmarijn.beckers@vlaamsbelang.org",
      "localImg": "flemish/4384.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Stijn",
      "lastName": "Bex",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4385",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "stijn.bex@vlaamsparlement.be",
      "localImg": "flemish/4385.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Adeline",
      "lastName": "Blancquaert",
      "city": "Brussel",
      "party": "VB",
      "id": "4386",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "adeline.blancquaert@vlaamsparlement.be",
      "localImg": "flemish/4386.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Robrecht",
      "lastName": "Bothuyne",
      "city": "Brussel",
      "party": "CD&V",
      "id": "3430",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "robrecht.bothuyne@kruisem.be",
      "localImg": "flemish/3430.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Jo",
      "lastName": "Brouns",
      "city": "Kinrooi",
      "party": "CD&V",
      "id": "4430",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "jo.brouns@vlaamsparlement.be",
      "localImg": "flemish/4430.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Karin",
      "lastName": "Brouwers",
      "city": "Brussel",
      "party": "CD&V",
      "id": "3426",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "karin.brouwers@vlaamsparlement.be",
      "localImg": "flemish/3426.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Filip",
      "lastName": "Brusselmans",
      "city": "Brussel",
      "party": "VB",
      "id": "4387",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "filip.brusselmans@vlaamsparlement.be",
      "localImg": "flemish/4387.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Yves",
      "lastName": "Buysse",
      "city": "Brussel",
      "party": "VB",
      "id": "4388",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "yves.buysse@vlaamsparlement.be",
      "localImg": "flemish/4388.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Lode",
      "lastName": "Ceyssens",
      "city": "Oudsbergen",
      "party": "CD&V",
      "id": "3388",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "lode.ceyssens@oudsbergen.be",
      "localImg": "flemish/3388.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Allessia",
      "lastName": "Claes",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4389",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "allessia.claes@n-va.be",
      "localImg": "flemish/4389.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bart",
      "lastName": "Claes",
      "city": "Brussel",
      "party": "VB",
      "id": "4390",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "bart.claes@vlaamsparlement.be",
      "localImg": "flemish/4390.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Arnout",
      "lastName": "Coel",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4444",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "arnout.coel@vlaamsparlement.be",
      "localImg": "flemish/4444.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Steven",
      "lastName": "Coenegrachts",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4446",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "steven.coenegrachts@vlaamsparlement.be",
      "localImg": "flemish/4446.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Cathy",
      "lastName": "Coudyser",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4068",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "cathy.coudyser@n-va.be",
      "localImg": "flemish/4068.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Johan",
      "lastName": "Danen",
      "city": "Bilzen",
      "party": "Ecolo-Groen",
      "id": "4069",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "johan.danen@groen.be",
      "localImg": "flemish/4069.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Koen",
      "lastName": "Daniëls",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4070",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "koen.daniels@vlaamsparlement.be",
      "localImg": "flemish/4070.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Piet",
      "lastName": "De Bruyn",
      "city": "Rotselaar",
      "party": "N-VA",
      "id": "3324",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "piet.debruyn@n-va.be",
      "localImg": "flemish/3324.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Johan",
      "lastName": "Deckmyn",
      "city": "Gent",
      "party": "VB",
      "id": "2838",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "johan.deckmyn@vlaamsparlement.be",
      "localImg": "flemish/2838.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Inez",
      "lastName": "De Coninck",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4391",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "inez.deconinck@vlaamsparlement.be",
      "localImg": "flemish/4391.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Jean-Jacques",
      "lastName": "De Gucht",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "3416",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "jean-jacques.degucht@vlaamsparlement.be",
      "localImg": "flemish/3416.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kurt",
      "lastName": "De Loor",
      "city": "Zottegem",
      "party": "sp.a",
      "id": "2791",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "kurt.deloor@vlaamsparlement.be",
      "localImg": "flemish/2791.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Ann",
      "lastName": "De Martelaer",
      "city": "Lubbeek",
      "party": "Ecolo-Groen",
      "id": "1781",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "ann.demartelaer@vlaamsparlement.be",
      "localImg": "flemish/1781.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Tom",
      "lastName": "De Meester",
      "city": "Brussel",
      "party": "PVDA-PTB",
      "id": "4401",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "tom.demeester@vlaamsparlement.be",
      "localImg": "flemish/4401.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Immanuel",
      "lastName": "De Reuse",
      "city": "Roeselare",
      "party": "VB",
      "id": "4432",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "Immanuel.dereuse@vlaamsparlement.be",
      "localImg": "flemish/4432.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Annick",
      "lastName": "De Ridder",
      "city": "Brussel",
      "party": "N-VA",
      "id": "2793",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "annick.deridder@vlaamsparlement.be",
      "localImg": "flemish/2793.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Maaike",
      "lastName": "De Rudder",
      "city": "Sint-gillis-waas",
      "party": "CD&V",
      "id": "4392",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "burgemeester@sint-gillis-waas.be",
      "localImg": "flemish/4392.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Maarten",
      "lastName": "De Veuster",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4393",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "maarten.deveuster@vlaamsparlement.be",
      "localImg": "flemish/4393.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Maaike",
      "lastName": "De Vreese",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4394",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "maaike.devreese@vlaamsparlement.be",
      "localImg": "flemish/4394.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Gwenny",
      "lastName": "De Vroe",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "3448",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "gwenny.devroe@vlaamsparlement.be",
      "localImg": "flemish/3448.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bart",
      "lastName": "De Wever",
      "city": "Brussel",
      "party": "N-VA",
      "id": "2796",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "bart.dewever@vlaamsparlement.be",
      "localImg": "flemish/2796.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Filip",
      "lastName": "Dewinter",
      "city": "Brussel",
      "party": "VB",
      "id": "1803",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "filip.dewinter@vlaamsparlement.be",
      "localImg": "flemish/1803.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kim",
      "lastName": "De Witte",
      "city": "Brussel",
      "party": "PVDA-PTB",
      "id": "4407",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "kim.dewitte@vlaamsparlement.be",
      "localImg": "flemish/4407.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Jos",
      "lastName": "D'Haese",
      "city": "Brussel",
      "party": "PVDA-PTB",
      "id": "4411",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "jos.dhaese@vlaamsparlement.be",
      "localImg": "flemish/4411.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Guy",
      "lastName": "D'haeseleer",
      "city": "Brussel",
      "party": "VB",
      "id": "4074",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "guy.dhaeseleer@vlaamsparlement.be",
      "localImg": "flemish/4074.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Stephanie",
      "lastName": "D'Hose",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4395",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "stephanie.dhose@vlaamsparlement.be",
      "localImg": "flemish/4395.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bart",
      "lastName": "Dochy",
      "city": "Ledegem",
      "party": "CD&V",
      "id": "4075",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "bart.dochy@vlaamsparlement.be",
      "localImg": "flemish/4075.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Sihame",
      "lastName": "El Kaouakibi",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4396",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "sihame.elkaouakibi@vlaamsparlement.be",
      "localImg": "flemish/4396.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Martine",
      "lastName": "Fournier",
      "city": "Menen",
      "party": "CD&V",
      "id": "3299",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "martine.fournier@vlaamsparlement.be",
      "localImg": "flemish/3299.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Caroline",
      "lastName": "Gennez",
      "city": "Brussel",
      "party": "sp.a",
      "id": "2836",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "caroline.gennez@s-p-a.be",
      "localImg": "flemish/2836.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Hannelore",
      "lastName": "Goeman",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4397",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "hannelore.goeman@vlaamsparlement.be",
      "localImg": "flemish/4397.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Celia",
      "lastName": "Groothedde",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4398",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "celia.groothedde@vlaamsparlement.be",
      "localImg": "flemish/4398.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Karolien",
      "lastName": "Grosemans",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4399",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "karolien.grosemans@vlaamsparlement.be",
      "localImg": "flemish/4399.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Andries",
      "lastName": "Gryffroy",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4077",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "andries.gryffroy@vlaamsparlement.be",
      "localImg": "flemish/4077.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Liesbeth",
      "lastName": "Homans",
      "city": "Brussel",
      "party": "N-VA",
      "id": "3411",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "liesbeth.homans@vlaamsparlement.be",
      "localImg": "flemish/3411.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Vera",
      "lastName": "Jans",
      "city": "Brussel",
      "party": "CD&V",
      "id": "2808",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "vera.jans@vlaamsparlement.be",
      "localImg": "flemish/2808.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Chris",
      "lastName": "Janssens",
      "city": "Brussel",
      "party": "VB",
      "id": "3418",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "chris.janssens@vlaamsparlement.be",
      "localImg": "flemish/3418.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Sofie",
      "lastName": "Joosen",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4078",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "sofie.joosen@vlaamsparlement.be",
      "localImg": "flemish/4078.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Marino",
      "lastName": "Keulen",
      "city": "Lanaken",
      "party": "Open Vld",
      "id": "1834",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "marino.keulen@vlaamsparlement.be",
      "localImg": "flemish/1834.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kathleen",
      "lastName": "Krekels",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4079",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "kathleen.krekels@vlaamsparlement.be",
      "localImg": "flemish/4079.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Jan",
      "lastName": "Laeremans",
      "city": "Brussel",
      "party": "VB",
      "id": "4400",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "jan.laeremans@telenet.be",
      "localImg": "flemish/4400.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Annick",
      "lastName": "Lambrecht",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4402",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "annick.lambrecht@vlaamsparlement.be",
      "localImg": "flemish/4402.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bert",
      "lastName": "Maertens",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4110",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "bert.maertens@vlaamsparlement.be",
      "localImg": "flemish/4110.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Ilse",
      "lastName": "Malfroot",
      "city": "Brussel",
      "party": "VB",
      "id": "4403",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "ilse.malfroot@vlaamsbelang.org",
      "localImg": "flemish/4403.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Marius",
      "lastName": "Meremans",
      "city": "Brussel",
      "party": "N-VA",
      "id": "3919",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "marius.meremans@n-va.be",
      "localImg": "flemish/3919.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Elisabeth",
      "lastName": "Meuleman",
      "city": "Oudenaarde",
      "party": "Ecolo-Groen",
      "id": "3173",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "elisabeth.meuleman@groen.be",
      "localImg": "flemish/3173.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "An",
      "lastName": "Moerenhout",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4058",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "an.moerenhout@vlaamsparlement.be",
      "localImg": "flemish/4058.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Philippe",
      "lastName": "Muyters",
      "city": "Brussel",
      "party": "N-VA",
      "id": "3461",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "philippe.muyters@vlaamsparlement.be",
      "localImg": "flemish/3461.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Joris",
      "lastName": "Nachtergaele",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4442",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "joris.nachtergaele@vlaamsparlement.be",
      "localImg": "flemish/4442.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Tom",
      "lastName": "Ongena",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4445",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "Tom.Ongena@vlaamsparlement.be",
      "localImg": "flemish/4445.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Katrien",
      "lastName": "Partyka",
      "city": "Tienen",
      "party": "CD&V",
      "id": "4059",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "burgemeester@tienen.be",
      "localImg": "flemish/4059.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Lorin",
      "lastName": "Parys",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4083",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "lorin@lorinparys.be",
      "localImg": "flemish/4083.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Gustaaf",
      "lastName": "Pelckmans",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4404",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "staf.pelckmans@groen.be",
      "localImg": "flemish/4404.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Freya",
      "lastName": "Perdaens",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4405",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "freya.perdaens@vlaamsparlement.be",
      "localImg": "flemish/4405.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Leo",
      "lastName": "Pieters",
      "city": "Maaseik",
      "party": "VB",
      "id": "3298",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "leo.pieters@vlaamsbelang.org",
      "localImg": "flemish/3298.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Els",
      "lastName": "Robeyns",
      "city": "Wellen",
      "party": "sp.a",
      "id": "3221",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "els.robeyns@vlaamsparlement.be",
      "localImg": "flemish/3221.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Tinne",
      "lastName": "Rombouts",
      "city": "Brussel",
      "party": "CD&V",
      "id": "2832",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "tinne.rombouts@vlaamsparlement.be",
      "localImg": "flemish/2832.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Axel",
      "lastName": "Ronse",
      "city": "Kortrijk",
      "party": "N-VA",
      "id": "4060",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "axel_ronse@hotmail.com",
      "localImg": "flemish/4060.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Conner",
      "lastName": "Rousseau",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4406",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "conner.rousseau@s-p-a.be",
      "localImg": "flemish/4406.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Gwendolyn",
      "lastName": "Rutten",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4061",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "gwendolyn.rutten@vlaamsparlement.be",
      "localImg": "flemish/4061.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Carmen",
      "lastName": "Ryheul",
      "city": "Brussel",
      "party": "VB",
      "id": "4408",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "carmen.ryheul@vlaamsbelang.org",
      "localImg": "flemish/4408.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Björn",
      "lastName": "Rzoska",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "3920",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "bjorn.rzoska@groen.be",
      "localImg": "flemish/3920.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Freya",
      "lastName": "Saeys",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4086",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "freya.saeys@vlaamsparlement.be",
      "localImg": "flemish/4086.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Joke",
      "lastName": "Schauvliege",
      "city": "Brussel",
      "party": "CD&V",
      "id": "2831",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "joke.schauvliege@vlaamsparlement.be",
      "localImg": "flemish/2831.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Mieke",
      "lastName": "Schauvliege",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4409",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "mieke.schauvliege@groen.be",
      "localImg": "flemish/4409.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Willem-Frederik",
      "lastName": "Schiltz",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4062",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "willem-frederik.schiltz@vlaamsparlement.be",
      "localImg": "flemish/4062.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Katrien",
      "lastName": "Schryvers",
      "city": "Brussel",
      "party": "CD&V",
      "id": "3433",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "katrien.schryvers@vlaamsparlement.be",
      "localImg": "flemish/3433.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Katia",
      "lastName": "Segers",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4087",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "katia.segers@vlaamsparlement.be",
      "localImg": "flemish/4087.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Stefaan",
      "lastName": "Sintobin",
      "city": "",
      "party": "VB",
      "id": "2825",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "stefaan.sintobin@vlaamsparlement.be",
      "localImg": "flemish/2825.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kristof",
      "lastName": "Slagmulder",
      "city": "Brussel",
      "party": "VB",
      "id": "4410",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "kristof.slagmulder@vlaamsbelang.org",
      "localImg": "flemish/4410.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Elke",
      "lastName": "Sleurs",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4088",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "elke.sleurs@n-va.be",
      "localImg": "flemish/4088.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Klaas",
      "lastName": "Slootmans",
      "city": "Brussel",
      "party": "VB",
      "id": "4412",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "klaas.slootmans@vlaamsparlement.be",
      "localImg": "flemish/4412.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Sarah",
      "lastName": "Smeyers",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4413",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "sarah.smeyers@n-va.be",
      "localImg": "flemish/4413.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Nadia",
      "lastName": "Sminate",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4089",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "nadia.sminate@n-va.be",
      "localImg": "flemish/4089.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Chris",
      "lastName": "Steenwegen",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4414",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "chris.steenwegen@groen.be",
      "localImg": "flemish/4414.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Els",
      "lastName": "Sterckx",
      "city": "Brussel",
      "party": "VB",
      "id": "4416",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "els.sterckx@vlaamsparlement.be",
      "localImg": "flemish/4416.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Emmily",
      "lastName": "Talpe",
      "city": "Ieper",
      "party": "Open Vld",
      "id": "4272",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "emmily.talpe@vlaamsparlement.be",
      "localImg": "flemish/4272.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Annabel",
      "lastName": "Tavernier",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4417",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "annabel.tavernier@vlaamsparlement.be",
      "localImg": "flemish/4417.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bruno",
      "lastName": "Tobback",
      "city": "Brussel",
      "party": "sp.a",
      "id": "1882",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "bruno.tobback@vlaamsparlement.be",
      "localImg": "flemish/1882.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Bart",
      "lastName": "Tommelein",
      "city": "Oostende",
      "party": "Open Vld",
      "id": "3434",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "bart@tommelein.be",
      "localImg": "flemish/3434.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Wilfried",
      "lastName": "Vandaele",
      "city": "Brussel",
      "party": "N-VA",
      "id": "3464",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "wilfried.vandaele@vlaamsparlement.be",
      "localImg": "flemish/3464.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Lise",
      "lastName": "Vandecasteele",
      "city": "Brussel",
      "party": "PVDA-PTB",
      "id": "4415",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "lise.vandecasteele@vlaamsparlement.be",
      "localImg": "flemish/4415.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Steve",
      "lastName": "Vandenberghe",
      "city": "Bredene",
      "party": "sp.a",
      "id": "4107",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "steve.vandenberghe@vlaamsparlement.be",
      "localImg": "flemish/4107.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Freya",
      "lastName": "Van den Bossche",
      "city": "Brussel",
      "party": "sp.a",
      "id": "3458",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "freya.vandenbossche@vlaamsparlement.be",
      "localImg": "flemish/3458.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Tine",
      "lastName": "Van den Brande",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4419",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "tine.vandenbrande@groen.be",
      "localImg": "flemish/4419.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Koen",
      "lastName": "Van den Heuvel",
      "city": "Puurs-sint-amands",
      "party": "CD&V",
      "id": "2815",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "koen.vandenheuvel@vlaamsparlement.be",
      "localImg": "flemish/2815.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Ludwig",
      "lastName": "Vandenhove",
      "city": "Sint-truiden",
      "party": "sp.a",
      "id": "4423",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "ludwig.vandenhove@vlaamsparlement.be",
      "localImg": "flemish/4423.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Steven",
      "lastName": "Vandeput",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4424",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "steven.vandeput@vlaamsparlement.be",
      "localImg": "flemish/4424.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Maurits",
      "lastName": "Vande Reyde",
      "city": "Brussel",
      "party": "Open Vld",
      "id": "4422",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "maurits.vandereyde@vlaamsparlement.be",
      "localImg": "flemish/4422.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Anke",
      "lastName": "Van dermeersch",
      "city": "Brussel",
      "party": "VB",
      "id": "4095",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "anke.vandermeersch@vlaamsparlement.be",
      "localImg": "flemish/4095.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Tine",
      "lastName": "van der Vloet",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4094",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "tine.vandervloet@vlaamsparlement.be",
      "localImg": "flemish/4094.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Orry",
      "lastName": "Van de Wauwer",
      "city": "Brussel",
      "party": "CD&V",
      "id": "4356",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "orry.vandewauwer@vlaamsparlement.be",
      "localImg": "flemish/4356.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kris",
      "lastName": "Van Dijck",
      "city": "Dessel",
      "party": "N-VA",
      "id": "1895",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "kris.vandijck@vlaamsparlement.be",
      "localImg": "flemish/1895.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Loes",
      "lastName": "Vandromme",
      "city": "Poperinge",
      "party": "CD&V",
      "id": "4425",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "loes.vandromme@vlaamsparlement.be",
      "localImg": "flemish/4425.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Jeremie",
      "lastName": "Vaneeckhout",
      "city": "Brussel",
      "party": "Ecolo-Groen",
      "id": "4426",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "jeremie.vaneeckhout@groen.be",
      "localImg": "flemish/4426.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Karl",
      "lastName": "Vanlouwe",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4102",
      "constituency": "Brussel-hoofdstad",
      "language": "Nederlands",
      "email": "karl.vanlouwe@vlaamsparlement.be",
      "localImg": "flemish/4102.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Paul",
      "lastName": "Van Miert",
      "city": "Turnhout",
      "party": "N-VA",
      "id": "4064",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "paul.vanmiert@vlaamsparlement.be",
      "localImg": "flemish/4064.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Vincent",
      "lastName": "Van Peteghem",
      "city": "Brussel",
      "party": "CD&V",
      "id": "4420",
      "constituency": "Oost-Vlaanderen",
      "language": "Nederlands",
      "email": "vincent.vanpeteghem@vlaamsparlement.be",
      "localImg": "flemish/4420.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Peter",
      "lastName": "Van Rompuy",
      "city": "Beersel",
      "party": "CD&V",
      "id": "3918",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "petervanrompuy@gmail.com",
      "localImg": "flemish/3918.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Sam",
      "lastName": "Van Rooy",
      "city": "Brussel",
      "party": "VB",
      "id": "4421",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "sam.vanrooy@vlaamsbelang.org",
      "localImg": "flemish/4421.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Kurt",
      "lastName": "Vanryckeghem",
      "city": "Waregem",
      "party": "CD&V",
      "id": "4427",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "kurt.vanryckeghem@vlaamsparlement.be",
      "localImg": "flemish/4427.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Mercedes",
      "lastName": "Van Volcem",
      "city": "Brugge",
      "party": "Open Vld",
      "id": "3444",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "mercedes.vanvolcem@vlaamsparlement.be",
      "localImg": "flemish/3444.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Manuela",
      "lastName": "Van Werde",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4099",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "manuela.vanwerde@vlaamsparlement.be",
      "localImg": "flemish/4099.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Wim",
      "lastName": "Verheyden",
      "city": "Bornem",
      "party": "VB",
      "id": "4433",
      "constituency": "Antwerpen",
      "language": "Nederlands",
      "email": "wim.verheyden@vlaamsbelang.org",
      "localImg": "flemish/4433.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Katja",
      "lastName": "Verheyen",
      "city": "Brussel",
      "party": "N-VA",
      "id": "4431",
      "constituency": "Limburg",
      "language": "Nederlands",
      "email": "katja.verheyen@vlaamsparlement.be",
      "localImg": "flemish/4431.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Frieda",
      "lastName": "Verougstraete-Deschacht",
      "city": "Oostende",
      "party": "VB",
      "id": "4434",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "frieda.verougstraete-deschacht@vlaamsparlement.be",
      "localImg": "flemish/4434.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Maxim",
      "lastName": "Veys",
      "city": "Brussel",
      "party": "sp.a",
      "id": "4428",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "maxim.veys@vlaamsparlement.be",
      "localImg": "flemish/4428.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Brecht",
      "lastName": "Warnez",
      "city": "Wingene",
      "party": "CD&V",
      "id": "4443",
      "constituency": "West-Vlaanderen",
      "language": "Nederlands",
      "email": "brecht.warnez@vlaamsparlement.be",
      "localImg": "flemish/4443.jpg"
  },
  {
      "parliament": "Vlaams Parlement",
      "firstName": "Suzy",
      "lastName": "Wouters",
      "city": "Brussel",
      "party": "VB",
      "id": "4429",
      "constituency": "Vlaams-brabant",
      "language": "Nederlands",
      "email": "suzy.wouters@vlaamsparlement.be",
      "localImg": "flemish/4429.jpg"
  }
];
