import { MP } from '../mp/mp';

export const members: MP[] = [
  {
      "parliament": "Parlement Wallon",
      "firstName": "Laurent",
      "lastName": "Agache",
      "city": "Templeuve",
      "party": "Ecolo-Groen",
      "id": "3254",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "l.agache@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3254.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Fatima",
      "lastName": "Ahallouch",
      "city": "Mouscron",
      "party": "PS",
      "id": "3191",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "f.ahallouch@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3191.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "André",
      "lastName": "Antoine",
      "city": "Perwez",
      "party": "cdH",
      "id": "53",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "a.antoine@parlement-wallonie.be",
      "twitter": "Andre_Antoine",
      "localImg": "walloon/53.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Christophe",
      "lastName": "Bastin",
      "city": "Gerin",
      "party": "cdH",
      "id": "3174",
      "constituency": "Dinant-philippeville",
      "language": "Frans",
      "email": "c.bastin@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3174.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Alice",
      "lastName": "Bernard",
      "city": "Liege",
      "party": "PVDA-PTB",
      "id": "3193",
      "constituency": "Liège",
      "language": "Frans",
      "email": "a.bernard@parlement-wallonie.be",
      "twitter": "@Alice_Bernrd",
      "localImg": "walloon/3193.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "John",
      "lastName": "Beugnies",
      "city": "Jemappes",
      "party": "PVDA-PTB",
      "id": "3175",
      "constituency": "Mons",
      "language": "Frans",
      "email": "j.beugnies@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3175.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Olivier",
      "lastName": "Bierin",
      "city": "Liege",
      "party": "Ecolo-Groen",
      "id": "2495",
      "constituency": "Liège",
      "language": "Frans",
      "email": "o.bierin@parlement-wallonie.be",
      "twitter": "OlivierBierin",
      "localImg": "walloon/2495.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Frederick",
      "lastName": "Botin",
      "city": "Ciney",
      "party": "MR",
      "id": "3197",
      "constituency": "Dinant-philippeville",
      "language": "Frans",
      "email": "f.botin@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3197.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Caroline",
      "lastName": "Cassart-mailleux",
      "city": "Ouffet",
      "party": "MR",
      "id": "1074",
      "constituency": "Huy-waremme",
      "language": "Frans",
      "email": "c.cassartmailleux@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1074.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Christophe",
      "lastName": "Clersy",
      "city": "Souvret",
      "party": "Ecolo-Groen",
      "id": "1508",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "c.clersy@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1508.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Christophe",
      "lastName": "Collignon",
      "city": "Huy",
      "party": "PS",
      "id": "1076",
      "constituency": "Huy-waremme",
      "language": "Frans",
      "email": "c.collignon@parlement-wallonie.be",
      "twitter": "christophehuy",
      "localImg": "walloon/1076.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "René",
      "lastName": "Collin",
      "city": "Marche-en-famenne",
      "party": "cdH",
      "id": "2339",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "r.collin@parlement-wallonie.be",
      "twitter": "Rene_Collin",
      "localImg": "walloon/2339.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Hervé",
      "lastName": "Cornillie",
      "city": "Pipaix",
      "party": "MR",
      "id": "2056",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "hervecornillie@hotmail.com",
      "twitter": "",
      "localImg": "walloon/2056.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Philippe",
      "lastName": "Courard",
      "city": "Hotton",
      "party": "PS",
      "id": "1077",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "p.courard@parlement-wallonie.be",
      "twitter": "CourardPhilippe",
      "localImg": "walloon/1077.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Veronica",
      "lastName": "Cremasco",
      "city": "Liege",
      "party": "Ecolo-Groen",
      "id": "561",
      "constituency": "Liège",
      "language": "Frans",
      "email": "v.cremasco@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/561.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Sybille",
      "lastName": "De coster-bauchau",
      "city": "Grez-doiceau",
      "party": "MR",
      "id": "1429",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "s.decosterbauchau@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1429.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Valérie",
      "lastName": "Delporte",
      "city": "Sombreffe",
      "party": "Ecolo-Groen",
      "id": "3172",
      "constituency": "Namur",
      "language": "Frans",
      "email": "v.delporte@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3172.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Rodrigue",
      "lastName": "Demeuse",
      "city": "Huy",
      "party": "Ecolo-Groen",
      "id": "3173",
      "constituency": "Huy-waremme",
      "language": "Frans",
      "email": "r.demeuse@parlement-wallonie.be",
      "twitter": "RDemeuse",
      "localImg": "walloon/3173.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Rudy",
      "lastName": "Demotte",
      "city": "Tournai",
      "party": "PS",
      "id": "100",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "r.demotte@parlement-wallonie.be",
      "twitter": "demotte",
      "localImg": "walloon/100.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "François",
      "lastName": "Desquesnes",
      "city": "Casteau",
      "party": "cdH",
      "id": "2286",
      "constituency": "Soignies-la louvière",
      "language": "Frans",
      "email": "f.desquesnes@parlement-wallonie.be",
      "twitter": "DESQUESNESF",
      "localImg": "walloon/2286.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Laurent",
      "lastName": "Devin",
      "city": "Leval",
      "party": "PS",
      "id": "1083",
      "constituency": "Soignies-la louvière",
      "language": "Frans",
      "email": "l.devin@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1083.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Michel",
      "lastName": "Di mattia",
      "city": "La louviere",
      "party": "PS",
      "id": "3182",
      "constituency": "Soignies-la louvière",
      "language": "Frans",
      "email": "m.dimattia@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3182.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Manu",
      "lastName": "Disabato",
      "city": "Frameries",
      "party": "Ecolo-Groen",
      "id": "1426",
      "constituency": "Mons",
      "language": "Frans",
      "email": "m.disabato@parlement-wallonie.be",
      "twitter": "manudisabato",
      "localImg": "walloon/1426.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Benoît",
      "lastName": "Dispa",
      "city": "Gembloux",
      "party": "cdH",
      "id": "3166",
      "constituency": "Namur",
      "language": "Frans",
      "email": "b.dispa@parlement-wallonie.be",
      "twitter": "BenoitDispa",
      "localImg": "walloon/3166.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Philippe",
      "lastName": "Dodrimont",
      "city": "Aywaille",
      "party": "MR",
      "id": "1424",
      "constituency": "Liège",
      "language": "Frans",
      "email": "p.dodrimont@parlement-wallonie.be\n",
      "twitter": "",
      "localImg": "walloon/1424.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Manu",
      "lastName": "Douette",
      "city": "Hannut",
      "party": "MR",
      "id": "3178",
      "constituency": "Huy-waremme",
      "language": "Frans",
      "email": "m.douette@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3178.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jori",
      "lastName": "Dupont",
      "city": "Blaton",
      "party": "PVDA-PTB",
      "id": "3188",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "j.dupont@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3188.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Véronique",
      "lastName": "Durenne",
      "city": "Molenbaix",
      "party": "MR",
      "id": "2279",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "v.durenne@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/2279.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Yves",
      "lastName": "Evrard",
      "city": "Neufchateau",
      "party": "MR",
      "id": "2277",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "y.evrard@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/2277.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jean-Philippe",
      "lastName": "Florent",
      "city": "Chiny",
      "party": "Ecolo-Groen",
      "id": "3187",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "jp.florent@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3187.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Eddy",
      "lastName": "Fontaine",
      "city": "Couvin",
      "party": "PS",
      "id": "2903",
      "constituency": "Dinant-philippeville",
      "language": "Frans",
      "email": "e.fontaine@parlement-wallonie.be",
      "twitter": "eddy_fontaine",
      "localImg": "walloon/2903.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "André",
      "lastName": "Frederic",
      "city": "Theux",
      "party": "PS",
      "id": "3170",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "a.frederic@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3170.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Paul",
      "lastName": "Furlan",
      "city": "Biercee",
      "party": "PS",
      "id": "103",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "p.furlan@parlement-wallonie.be",
      "twitter": "paul_furlan",
      "localImg": "walloon/103.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Latifa",
      "lastName": "Gahouchi",
      "city": "Lodelinsart",
      "party": "PS",
      "id": "1913",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "l.gahouchi@parlement-wallonie.be",
      "twitter": "latifagahouchi",
      "localImg": "walloon/1913.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jacqueline",
      "lastName": "Galant",
      "city": "Jurbise",
      "party": "MR",
      "id": "528",
      "constituency": "Mons",
      "language": "Frans",
      "email": "j.galant@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/528.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Charles",
      "lastName": "Gardier",
      "city": "Spa",
      "party": "MR",
      "id": "2943",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "c.gardier@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/2943.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Anne-Catherine",
      "lastName": "Goffinet",
      "city": "Arlon",
      "party": "cdH",
      "id": "1415",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "ac.goffinet@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1415.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Alda",
      "lastName": "Greoli",
      "city": "Liege",
      "party": "cdH",
      "id": "606",
      "constituency": "Liège",
      "language": "Frans",
      "email": "a.greoli@parlement-wallonie.be",
      "twitter": "aldagreoli",
      "localImg": "walloon/606.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Gwenaëlle",
      "lastName": "Grovonius",
      "city": "Namur",
      "party": "PS",
      "id": "3165",
      "constituency": "Namur",
      "language": "Frans",
      "email": "g.grovonius@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3165.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Maxime",
      "lastName": "Hardy",
      "city": "Marcinelle",
      "party": "PS",
      "id": "3340",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "m.hardy@parlement-wallonie.be",
      "twitter": "maximardy",
      "localImg": "walloon/3340.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Stéphane",
      "lastName": "Hazee",
      "city": "Namur",
      "party": "Ecolo-Groen",
      "id": "1133",
      "constituency": "Namur",
      "language": "Frans",
      "email": "s.hazee@parlement-wallonie.be",
      "twitter": "steph_le_vert",
      "localImg": "walloon/1133.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Antoine",
      "lastName": "Hermant",
      "city": "La louviere",
      "party": "PVDA-PTB",
      "id": "3181",
      "constituency": "Soignies-la louvière",
      "language": "Frans",
      "email": "a.hermant@parlement-wallonie.be",
      "twitter": "ahermant",
      "localImg": "walloon/3181.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Laurent",
      "lastName": "Heyvaert",
      "city": "Clabecq",
      "party": "Ecolo-Groen",
      "id": "3168",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "l.heyvaert@parlement-wallonie.be",
      "twitter": "heyvaertlaurent",
      "localImg": "walloon/3168.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Nicolas",
      "lastName": "Janssen",
      "city": "La hulpe",
      "party": "MR",
      "id": "3252",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "n.janssen@parlement-wallonie.be",
      "twitter": "NicolasJanssen6",
      "localImg": "walloon/3252.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Joëlle",
      "lastName": "Kapompole",
      "city": "Mons",
      "party": "PS",
      "id": "1090",
      "constituency": "Mons",
      "language": "Frans",
      "email": "j.kapompole@parlement-wallonie.be",
      "twitter": "kapompole",
      "localImg": "walloon/1090.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Anne",
      "lastName": "Kelleter",
      "city": "Eupen",
      "party": "Ecolo-Groen",
      "id": "3189",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "a.kelleter@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3189.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Anne",
      "lastName": "Laffut",
      "city": "Ochamps",
      "party": "MR",
      "id": "3186",
      "constituency": "Arlon-bastogne-marche-en-famenne-neufchâteau-virton",
      "language": "Frans",
      "email": "a.laffut@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3186.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Sabine",
      "lastName": "Laruelle",
      "city": "Gembloux",
      "party": "MR",
      "id": "3169",
      "constituency": "Namur",
      "language": "Frans",
      "email": "s.laruelle@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3169.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Dimitri",
      "lastName": "Legasse",
      "city": "Rebecq",
      "party": "PS",
      "id": "2268",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "d.legasse@parlement-wallonie.be",
      "twitter": "DimitriLegasse",
      "localImg": "walloon/2268.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Laure",
      "lastName": "Lekane",
      "city": "Vivegnis",
      "party": "PVDA-PTB",
      "id": "3192",
      "constituency": "Liège",
      "language": "Frans",
      "email": "l.lekane@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3192.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Mauro",
      "lastName": "Lenzini",
      "city": "Oupeye",
      "party": "PS",
      "id": "1444",
      "constituency": "Liège",
      "language": "Frans",
      "email": "m.lenzini@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1444.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Laurent",
      "lastName": "Leonard",
      "city": "Flemalle",
      "party": "PS",
      "id": "3253",
      "constituency": "Liège",
      "language": "Frans",
      "email": "l.leonard@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3253.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jean-Pierre",
      "lastName": "Lepine",
      "city": "Quaregnon",
      "party": "PS",
      "id": "3180",
      "constituency": "Mons",
      "language": "Frans",
      "email": "jp.lepine@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3180.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Julien",
      "lastName": "Liradelfo",
      "city": "Herstal",
      "party": "PVDA-PTB",
      "id": "3183",
      "constituency": "Liège",
      "language": "Frans",
      "email": "j.liradelfo@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3183.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jean-Charles",
      "lastName": "Luperto",
      "city": "Sambreville",
      "party": "PS",
      "id": "1091",
      "constituency": "Namur",
      "language": "Frans",
      "email": "jc.luperto@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/1091.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jean-Claude",
      "lastName": "Marcourt",
      "city": "Liege",
      "party": "PS",
      "id": "1102",
      "constituency": "Liège",
      "language": "Frans",
      "email": "jc.marcourt@parlement-wallonie.be",
      "twitter": "jcmarcourt",
      "localImg": "walloon/1102.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Olivier",
      "lastName": "Maroy",
      "city": "Orp-jauche",
      "party": "MR",
      "id": "2285",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "o.maroy@parlement-wallonie.be",
      "twitter": "@oliviermaroy",
      "localImg": "walloon/2285.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Julien",
      "lastName": "Matagne",
      "city": "Thuin",
      "party": "cdH",
      "id": "3176",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "j.matagne@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3176.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Françoise",
      "lastName": "Mathieux",
      "city": "Couvin",
      "party": "MR",
      "id": "3185",
      "constituency": "Dinant-philippeville",
      "language": "Frans",
      "email": "f.mathieux@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3185.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Christine",
      "lastName": "Mauel",
      "city": "Raeren",
      "party": "MR",
      "id": "3171",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "c.mauel@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3171.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Germain",
      "lastName": "Mugemangango",
      "city": "Marcinelle",
      "party": "PVDA-PTB",
      "id": "2361",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "g.mugemangango@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/2361.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Samuel",
      "lastName": "Nemes",
      "city": "Namur",
      "party": "PVDA-PTB",
      "id": "3164",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "s.nemes@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3164.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Diana",
      "lastName": "Nikolic",
      "city": "Liege",
      "party": "MR",
      "id": "3097",
      "constituency": "Liège",
      "language": "Frans",
      "email": "d.nikolic@parlement-wallonie.be",
      "twitter": "DianaNikolic",
      "localImg": "walloon/3097.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Amandine",
      "lastName": "Pavet",
      "city": "Ecaussinnes",
      "party": "PVDA-PTB",
      "id": "3194",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "a.pavet@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3194.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Sophie",
      "lastName": "Pecriaux",
      "city": "Seneffe",
      "party": "PS",
      "id": "1416",
      "constituency": "Soignies-la louvière",
      "language": "Frans",
      "email": "s.pecriaux@parlement-wallonie.be",
      "twitter": "pecriauxsophie",
      "localImg": "walloon/1416.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Sabine",
      "lastName": "Roberty",
      "city": "Ougree",
      "party": "PS",
      "id": "3184",
      "constituency": "Liège",
      "language": "Frans",
      "email": "s.roberty@parlement-wallonie.be",
      "twitter": "https://www.twitter.com/@SabineRoberty",
      "localImg": "walloon/3184.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Hélène",
      "lastName": "Ryckmans",
      "city": "Cortil-noirmont",
      "party": "Ecolo-Groen",
      "id": "2290",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "h.ryckmans@parlement-wallonie.be",
      "twitter": "heleneryckmans",
      "localImg": "walloon/2290.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Mourad",
      "lastName": "Sahli",
      "city": "Chapelle-lez-herlaimont",
      "party": "PS",
      "id": "3177",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "m.sahli@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3177.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Marie-Martine",
      "lastName": "Schyns",
      "city": "Herve",
      "party": "cdH",
      "id": "2287",
      "constituency": "Verviers",
      "language": "Frans",
      "email": "mm.schyns@parlement-wallonie.be",
      "twitter": "MM_Schyns",
      "localImg": "walloon/2287.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Rachel",
      "lastName": "Sobry",
      "city": "Charleroi",
      "party": "MR",
      "id": "3179",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "r.sobry@parlement-wallonie.be",
      "twitter": "SobryRachel",
      "localImg": "walloon/3179.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Nicolas",
      "lastName": "Tzanetatos",
      "city": "Charleroi",
      "party": "MR",
      "id": "2298",
      "constituency": "Charleroi-thuin",
      "language": "Frans",
      "email": "n.tzanetatos@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/2298.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Anouk",
      "lastName": "Vandevoorde",
      "city": "Namur",
      "party": "PVDA-PTB",
      "id": "3167",
      "constituency": "Namur",
      "language": "Frans",
      "email": "a.vandevoorde@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3167.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Mathilde",
      "lastName": "Vandorpe",
      "city": "Mouscron",
      "party": "cdH",
      "id": "2300",
      "constituency": "Tournai-ath-mouscron",
      "language": "Frans",
      "email": "m.vandorpe@parlement-wallonie.be",
      "twitter": "m_vandorpe",
      "localImg": "walloon/2300.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Jean-Paul",
      "lastName": "Wahl",
      "city": "Jodoigne",
      "party": "MR",
      "id": "51",
      "constituency": "Nivelles",
      "language": "Frans",
      "email": "jp.wahl@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/51.jpg"
  },
  {
      "parliament": "Parlement Wallon",
      "firstName": "Thierry",
      "lastName": "Witsel",
      "city": "Liege",
      "party": "PS",
      "id": "3190",
      "constituency": "Liège",
      "language": "Frans",
      "email": "t.witsel@parlement-wallonie.be",
      "twitter": "",
      "localImg": "walloon/3190.jpg"
  }
];
